### ISSUE TITLE
Feature request: Support for relative mouse movements

### ISSUE THREAD

**Issue by badda71** [ultravnc/UltraVNC#1]
Sometimes applications require relative mouse movements rather than an absolute position. Especially 3D-games are not playable with absolute mouse movements, only relative ones (almost all 3D games). I tested this with RealVNC - RealVNC supports relative mouse movements and there, the games are playable. However, RealVNC uses a proprietary protocol extension for this.
UltraVNC could be easily extended using the General Input Interface extension (gii pseudo-encoding).
This would have the additional benefit of adding Joystick/Gamepad support to UltraVNC.

**Comment by Neustradamus** [comment]
Linked to:
- https://forum.ultravnc.net/viewtopic.php?f=4&t=36860
