### ISSUE TITLE
Auto-scaling issue when listening UltraVNC Viewer is in a non-active remote desktop session

### ISSUE THREAD

**Issue by panreyes** [ultravnc/UltraVNC#100]
When using autoscaling, it won't work correctly if UltraVNC Viewer is in a non-active remote desktop session when the UltraVNC Server starts a reverse connection.

Steps to reproduce it:
1. Configure UltraVNC Viewer in a Windows Pro / Server with Remote Desktop enabled.
2. Access that computer+user session through Remote Desktop.
3. Close (don't log off!) the Remote Desktop connection.
4. In another PC, Launch UltraVNC Server with a reverse connection to that UltraVNC Viewer.
5. Access that Remote Desktop again. The window will be extremely huge.

Reported screen work area in UltraVNC Viewer log: 
```
Desktop name "win-7b6bg55ipn0 ( 192.168.1.188 ) - service mode "
Geometry 1024 x 768 depth 24
Screen work area is 1954081 x 11207611
Autosize 190826
Clipboard changed
Ignore Clipboard while initializing!
Screen work area is -1950356 x -1994172355
```

Screenshot of the issue (Pay attention to the scroll bar size!):
![image](https://github.com/ultravnc/UltraVNC/assets/13276823/9d17d0ba-3aa9-4e68-8fa5-404038cf61e1)

It's not an important issue for me because the UltraVNC Server is configured to automatically reconnect, so if I just close the huge window it will get back with the expected scaling.

A possible workaround would be to find out if the reported work desktop size is huge and disable the autoscaling for that connection, or use a previous saved one. I believe the changes should be done around here:
https://github.com/ultravnc/UltraVNC/blob/6a0453045421071ab1c0a7067fb4899344dcb954/vncviewer/ClientConnection.cpp#L3762

**Comment by Neustradamus** [comment]
@RudiDeVos: Have you seen this ticket?

**Comment by RudiDeVos** [comment]
A non active rdp session does not have a active video card.
The size is not initialized and can have any value

I simple hack could be to set 1024x768 as default when size is bigger then a 4k resolution, just to prevent the viewer using a lot of memory. I don't expect it to work proper without proper video value's

**Comment by RudiDeVos** [comment]
pushed as #100

**Comment by panreyes** [comment]
Thanks! 🙌
In any case, I would also take into account that sometimes the reported "Screen work area" X,Y are less than zero as it was reported in the logs. It might be helpful to have the condition check that too, just in case:
```
if (workwidth > 4320 || workheight > 4320 || workwidth < 1 || workheight < 1) {
```
