### ISSUE TITLE
Cannot File Transfer folder with files in VNC Viewer 1430+

### ISSUE THREAD

**Issue by gspbeetle** [ultravnc/UltraVNC#101]
Cannot direct transfer whole folder with files after viewer 1.4.3.0+ with server 1.4.3.0+
Does not create compressed zip file during folder transfer like previous versions.
Transfer multiple files without folder still works.
Downgrade to V1.4.2.0 will work again for whole folder transfer
Note: Using VNC Viewer with SecureVNCPlugin-v2.4.10

**Comment by gspbeetle** [comment]
Seems to be only viewer side bug.
Using Server 1.4.3.0 with Viewer 1.4.2.0 still works.
Also tried with another client PC, also same results.

**Comment by gspbeetle** [comment]
![1 4 3 1](https://github.com/ultravnc/UltraVNC/assets/33320637/b2506a3a-63a6-43d6-bc7c-2c3a62b05207)
co
![1 4 2 0](https://github.com/ultravnc/UltraVNC/assets/33320637/d5019f0a-fb4e-45dc-96f0-cef711453c27)
confirmed viewer only bug, attached pics

**Comment by Neustradamus** [comment]
@RudiDeVos: Can you look this issue?

**Comment by RudiDeVos** [comment]
Commited as  "fIx Cannot File Transfer folder with files in VNC Viewer 1430+ #101"

**Comment by Neustradamus** [comment]
@gspbeetle: Have you tested the latest dev build?
- https://forum.uvnc.com/viewtopic.php?t=37855

It is good? This ticket can be closed?
