### ISSUE TITLE
VncViewer 1.4.3.1: freeze and crash after lock/unlock local user

### ISSUE THREAD

**Issue by pdbtva** [ultravnc/UltraVNC#104]
Hi,
This always happens.
When you have a connection with vncclient from a local PC to a remote PC and Windows locks the local user, when you unlock the user again, the vncviewer screen is black.
Any attempt to refresh the screen or send keys through vncviewer causes vncviewer to crash.

I have been using this program for years and in previous versions this did not happen... It will be another Windows problem hehe ... =;-P

Does anyone else have this problem?

Thank a lot!!
Good Job!

**Comment by Neustradamus** [comment]
@RudiDeVos: Have you seen the @pdbtva ticket?

**Comment by RudiDeVos** [comment]
Under investigation, trying to repeat it

**Comment by pdbtva** [comment]
[Uvnc.zip](https://github.com/ultravnc/UltraVNC/files/12646255/Uvnc.zip)
Hi!
I attach the files as you asked...
Thanks!

**Comment by RudiDeVos** [comment]
Sorry, can't repeat it,  i disable UAC for testing as the result could be different.

Possible what you see is the following.

When you start winvnc.exe as normal user, VNC doesn't have permission to access other desktops.
Logon/unlock windows are OS protected and require higher permission.
When you run as normal user, the user in front of the remote PC need to unlock it for you, else you are locked out.

To run in another desktop winvnc need to be started as service or "run as admin".  
In that case you can unlock the screen from the viewer site.

**Comment by pdbtva** [comment]
Hi, 
I'm sorry, but I can't tell you much more.
The uvncserver starts as a service and does not cause any problems, apparently it is only the UVNCViewer that fails.
This happens even when the remote's screensaver is disabled.

After unlocking the user or the screensaver (in the PC with UVNCViewer), first the black screen appears, then gray, and after a while crash.
can we have a UVNCViewer logging?

thanks!

![LockUVNC3](https://github.com/ultravnc/UltraVNC/assets/15889430/d84bce3b-3ca8-4a6b-9ec2-76df7acb9c1f)
![LockUVNC2](https://github.com/ultravnc/UltraVNC/assets/15889430/34ad692f-7b0d-4cfc-b91e-29f6897f5c1b)
![LockUVNC](https://github.com/ultravnc/UltraVNC/assets/15889430/98f62aac-ac5f-4f9e-8a70-8ad5cfe4e3a6)

**Comment by RudiDeVos** [comment]
Yes, the viewer also has logging
Start the viewer from commandline

-loglevel loglevel
Set the loglevel. This can range from 0 (minimal) to 10 (maximum logging).
-console
Open a console window for log output.
-logfile filename
Log to the file specified by filename.

**Comment by pdbtva** [comment]
[uvnc.log](https://github.com/ultravnc/UltraVNC/files/12735669/uvnc.log)
Hi, this is the log file.
Steps:
Open and connect UVNCViewer -> Correct
Lock Windows User on PC with Viewer
Unlock User
Black window in UVNCViewer screen
Gray window in UVNCViewer screen 
Crash UVNCViewer

I'm going to try the new version 1.4.3.5, and I'll tell you something else
bye

**Comment by RudiDeVos** [comment]
Something strange
Geometry 1680 x 1050
Screen work area is 2048 x 1112
But this doesn't seems to crash it...

I would expect that de workspace is a little smaller then the geo
Have you some special screen setup ?

Can you test with another PC as viewer, does this have the same issue.

Test myself with Lock/screensavers etc... but just can get it crash, no crash no way to find the clue

**Comment by pdbtva** [comment]
Hi, 
I have tried the new version 1.4.3.5 and **it doesn't crash.**

I only see one detail in the connection with a remote PC with two monitors, when I unlock the user in PC Viewer, the viewer screen remains black until you change the remote monitor using the "Switch Monitor" button.

Thanks for fix the crash problem, good job.

¿do you need help for spanish translate?

**Comment by RudiDeVos** [comment]
Nice to hear

**Comment by Neustradamus** [comment]
@pdbtva: Can you try the latest version?
- https://forum.uvnc.com/viewforum.php?f=56

About your sentence, it has been solved or not?
"I only see one detail in the connection with a remote PC with two monitors, when I unlock the user in PC Viewer, the viewer screen remains black until you change the remote monitor using the "Switch Monitor" button."

If not, can you create a new ticket with a lot of details?
