### ISSUE TITLE
can UltraVNC server work under windows virtual desktop environment?

### ISSUE THREAD

**Issue by Chingliu** [ultravnc/UltraVNC#105]
As the title description, is there any way to make UltraVNC work under virtual desktop? 
Thanks

**Comment by Neustradamus** [comment]
@RudiDeVos: Have you seen the @Chingliu ticket?

**Comment by RudiDeVos** [comment]
Isn't it working ?
What's the problem you have ?

**Comment by eebssk1** [comment]
With my past experience, UVNC does not engage in RDP desktop because it's not a terminal sesion.

**Comment by RudiDeVos** [comment]
Any vnc clone the console running as service and the active desktop as application.
When you you run UltraVnc as service ther icon is visible on the console not in the RDP session.

But:  UltraVnc has an experimental option (RDPmode) when this is active
1) The server give you a list of all connected rdp session + console
2) When the viewer connect you get some input screen, make your session selection ( console or any active RDP)
3) Then the viewer continue and make a connection to the selected session

**Comment by RudiDeVos** [comment]
UltraVNC works with vmware and virtual PC, we never trying the azure virtual desktop, but it looks like just some virtual pc hosten in the cloud.  Should work.

Hardest gonna be the bypass the azure network security

**Comment by eebssk1** [comment]
> Any vnc clone the console running as service and the active desktop as application.
> When you you run UltraVnc as service ther icon is visible on the console not in the RDP session.
> 
> But:  UltraVnc has an experimental option (RDPmode) when this is active
> 1) The server give you a list of all connected rdp session + console
> 2) When the viewer connect you get some input screen, make your session selection ( console or any active RDP)
> 3) Then the viewer continue and make a connection to the selected session

Does rdp mode work on official realvnc viewer or any other viewer on Android?

**Comment by RudiDeVos** [comment]
It should be flavor independed, as it's a server setting  But, we only tested it with UltraVNC
