### ISSUE TITLE
VNC server crashes when too many IPv6 interfaces present

### ISSUE THREAD

**Issue by alexeikom** [ultravnc/UltraVNC#107]
In **vncclient.cpp**, **desktopname** char buffer is 274 bytes. 256 bytes are for IP addresses string. When there are too many interfaces (IPv6, for example, since those are long), we get a long string, approaching the 256 bytes limit (**szIP**). In such a case, **strcat_s(desktopname, "application mode");**    (**vncclient.cpp, line 2328**) crashes the server since there is no room for appending "application mode" or "service mode" strings (256 bytes are taken by IPs string, 15 for the hostname and 3 for spaces and bracket. No room for additional chars).

**Comment by Neustradamus** [comment]
@RudiDeVos: Have you seen the @alexeikom ticket?

**Comment by RudiDeVos** [comment]
updated 
thanks

wil be in 1.4.3.4-dev
