### ISSUE TITLE
Version incompatibility

### ISSUE THREAD

**Issue by tmcmi** [ultravnc/UltraVNC#109]
I have a server running 1.2.2.4, and file transfer was slowing down with time as usual.
I updated the viewer to UltraVNC_1431_X64, but now file transfer finished instantly without transferring the file.
I uninstalled and reinstalled the 1.2.2.4 viewer, restarted the service on the server, deleted the temporary files and file transfer worked.
This process was repeatable.

**Comment by Neustradamus** [comment]
@tmcmi: Have you updated your server too?
When you install on the server, you must to restart to have the last version on it.

Can you test the 1.4.3.3-dev?
- https://forum.uvnc.com/viewtopic.php?t=37855

cc: @RudiDeVos.

**Comment by tmcmi** [comment]
Unfortunately, I can't update the server as it's not my machine.
The dev build works, albeit with the same slow down behaviour the same as the 1.2.2.4 build.

**Comment by Neustradamus** [comment]
@tmcmi: Can you request a UltraVNC server update at the server admin?
At this time, it is better to update to 1.4.3.3-dev.

**Comment by Neustradamus** [comment]
@tmcmi: 1.4.3.5 has been released!
- https://forum.uvnc.com/viewforum.php?f=56
