### ISSUE TITLE
Infinite loop w/ error message during uvnc server startup

### ISSUE THREAD

**Issue by badda71** [ultravnc/UltraVNC#11]
I just downloaded the "ultravnc 1.3.2 bin zip" and tried to start the server executable (without admin priviledges). However, for both 32 and 64-bit servers, I'm getting the following error message in an infinite loop. To stop the error message from appearing, I need to kill the process using task manager. System: Windows 10 Enterprise, ver 1909.
![grafik](https://user-images.githubusercontent.com/11392517/107430790-ee3eff00-6b25-11eb-90df-a62ead7f2791.png)

**Comment by Neustradamus** [comment]
@RudiDeVos: Please look it?

**Comment by RudiDeVos** [comment]
You need to set a password.
Ultravnc prevent the server to start and keeps asking for a password.

**Comment by badda71** [comment]
Yeah, but how can I set a password if I cannot even get the server to start?

**Comment by Neustradamus** [comment]
@badda71, @RudiDeVos: It can be closed?

**Comment by Neustradamus** [comment]
@badda71: This ticket can be closed?

**Comment by badda71** [comment]
I cannot reproduce the behaviour anymore, so closing this issue
