### ISSUE TITLE
not support visual studio 2022

### ISSUE THREAD

**Issue by introspection3** [ultravnc/UltraVNC#114]
![image](https://github.com/ultravnc/UltraVNC/assets/12368358/846dde1b-2104-4a40-ba79-29e60b78ba20)

**Comment by RudiDeVos** [comment]
"microsoft visual studio installer projects" is a seperate download via 
Visual studio "Manage extenstion"
This exist also for 2022
![image](https://github.com/ultravnc/UltraVNC/assets/71467484/9905aac4-b320-45b5-87e5-5695decbd8ec)
