### ISSUE TITLE
have virus ?

### ISSUE THREAD

**Issue by oper1000** [ultravnc/UltraVNC#115]
i'm sorry but my antivirus software tips me it have virus

![image](https://github.com/ultravnc/UltraVNC/assets/993995/b8d43065-1a1c-47e4-8470-1320bc5c63ee)

![image](https://github.com/ultravnc/UltraVNC/assets/993995/40bb7507-a746-40d0-a782-bfb273fba574)

SO..... i need some MD5 about Setup or exe file ,so i can check where's problem.

is these OK?

**Comment by RudiDeVos** [comment]
Alle hashes added on website

![afbeelding](https://github.com/ultravnc/UltraVNC/assets/71467484/bf047c5f-2ec6-4914-9e49-e26c09c3a305)

**Comment by Neustradamus** [comment]
@oper1000: Official UltraVNC builds are not a virus but some Antivirus detect like a Remote App...

**Comment by oper1000** [comment]
> @oper1000: Official UltraVNC builds are not a virus but some Antivirus detect like a Remote App...

That's a trouble thing.have any idea to solve ?

**Comment by Neustradamus** [comment]
@oper1000: I think you must to add UltraVNC in your Antivirus like safe software (if you have downloaded from official website).
