### ISSUE TITLE
Start Menu Can not display the sub menu

### ISSUE THREAD

**Issue by oper1000** [ultravnc/UltraVNC#116]
![image](https://github.com/ultravnc/UltraVNC/assets/993995/28b7cb19-583c-419d-87f8-e48f321d21b1)

see the photo up

**Comment by oper1000** [comment]
New: sometime if try Reconntion sometimes ,it will display
         and sometime it will keep not display.

**Comment by Neustradamus** [comment]
@oper1000: Normally it is not here but at left, all programs.
