### ISSUE TITLE
Server Ignores All but Last when using multiple -connect options

### ISSUE THREAD

**Issue by zellchristensen** [ultravnc/UltraVNC#123]
When launching winvnc.exe with multiple -connect flags, only the last one is actually used. 

For example, when running the following:
winvnc.exe -autoreconnect -connect 10.24.7.100 -connect 10.24.8.212 -run

The server will only attempt to connect to 10.24.8.212 and no attempts to connect to 10.24.7.100 are made.

![procexp64_KKV5BoXXjT](https://github.com/ultravnc/UltraVNC/assets/38737447/1a54ab78-2ffa-4c79-b108-b86287ff5e99)

I can work around this by launching the same command with only -connect 10.24.7.100 which causes an error message that the server is already running but will force the existing instance to open the new connection in addition.

![winvnc_YGhByzkjBy](https://github.com/ultravnc/UltraVNC/assets/38737447/f0ce93c8-e647-4a80-888f-b2b697e43fde)

![procexp64_qAfHkRbSPE](https://github.com/ultravnc/UltraVNC/assets/38737447/cbdd3429-a97c-4ffc-820f-624ad229c18f)

This was tested initially on build 1409 on Windows 10 operating only in user mode, no service, using startup flags.
Confirmed same behavior on build 1436 in user mode.
Build 1436 in Service Mode also connects only to the last entry but I'm unable to start a new instance to force the secondary connection

**Comment by RudiDeVos** [comment]
winvnc.exe -autoreconnect -connect 10.24.7.100 -connect 10.24.8.212 -run
This is not supported in any build

**Comment by RudiDeVos** [comment]
Retested today.
changed AllowInjection=0 to 1 in ultravnc.ini
started winvnc as service
from commandline winvnc -connect xxx
This still works on my PC.
No need to start  winvnc -connect xx  with runas admin
Possible you have AllowInjection=0 and AllowInjection=1 in the ini i didn't needed to add it, just changing it.

Doc changed
added OR : and :: makes a difference
[-connect host[:port]] OR [-connect host[::port]]

**Comment by zellchristensen** [comment]
Yes it works fine with AllowInjection=1.
With AllowInjection=0 using Admin mode to run it a second time, it doesn't not connect. It requires the AllowInjection=1
