### ISSUE TITLE
Keyboard and mouse events are transferred and handled on vnc server but image is not updated in vnc viewer

### ISSUE THREAD

**Issue by ulrike70** [ultravnc/UltraVNC#128]
I'm facing the issue in the following environment:
- VNC server running as service (unfortunately it will not possible to update the VNC server to the latest version)
- VNC viewer (1.4.3.6, x64, "installed" from zip) in Windows Server 2022 (deployed as VM) with RDP server running, both cursors are visible
- RDP client running on developer computer (Windows 10)

The scenario is:
- RDP connects to VM with Windows Server 2022
- VNC viewer is started and successfully connected to the VNC server
- RDP client is minimized (this will set the VM as far as I know into a GUI-less mode)
- after a few seconds the RDP client is restored and you can move/click the mouse and also press keys (and these actions are executed on the VNC Server side !!!)

What happens is:
- sometimes the viewer instantly resumes and you see instantly what you do on the VNC server side
- if not
  - in the best case it starts with a black screen with a kind of blocks until after 5-10 seconds the vnc viewer is refreshed completely
  - next case is that it takes 5-10 seconds until the vnc viewer is refreshed and you see again what happens on the VNC server side (and what you might have clicked in the meantime)
  - worst case is that the VNC viewer is completely frozen (i.e. you won't get a reaction at all), in this case even the 'Refresh Screen' button won't work, you can only open the 'Connection dialog' and click OK or close the VNC viewer and restart it; then you see what you have did :-(

It seems that the vnc viewer does not return to a proper working state after resuming from the gui-less mode. It also happened once after locking and unlocking the developer computer.

Here the options.vnc file used to start the VNC Viewer:
[options.vnc.txt](https://github.com/ultravnc/UltraVNC/files/13707964/options.vnc.txt)

**Comment by ulrike70** [comment]
I tried to find possible causes in the code and as I started the VNC Viewer with full debug logging I encountered the following pattern in the log. After restoring the rdp client window the vnc viewer window got the focus and the log contained the following lines:

```
Reset keyboard for first use
Flush dead key gives: 1 character(s): 0x0020 ( )

PCtoX: virtKey 0x09 up, keyData 0x800f0001
Release the associated KeySym when this VirtKey was pressed
  Control character: No associated KeySym
```

Maybe a fix would be to update the Framebuffer in this case, too (i.e. when the WM_SETFOCUS is handled).

**Comment by RudiDeVos** [comment]
Adding an extra full update after focus will not flood anything, it's not that you take focus every second.
This can be done easy, i only don't know if it solve this specific issue but it will not  destroy anything.

Thanks for the suggestion.

**Comment by joachimd-trumpf** [comment]
Hi i am colleague from Ulrike and tried to track down the problem further, i think i found it and a solution to it, if you could take the time for a PR we would be thankfull.

Best Regards

https://github.com/ultravnc/UltraVNC/pull/130

**Comment by RudiDeVos** [comment]
Sorry for the late answer, just back.
Will check it

**Comment by Neustradamus** [comment]
@ulrike70, @joachimd-trumpf: Have you possibility to test it on another VM?

**Comment by Neustradamus** [comment]
@ulrike70, @joachimd-trumpf: Have you possibility to test it on another VM?

**Comment by ulrike70** [comment]
Sorry for the late feedback. We tested the fix in the meantime in lots of VMs and heard no complaints.
