### ISSUE TITLE
How to set not to create UltraVNC.ini

### ISSUE THREAD

**Issue by SnowMeteors** [ultravnc/UltraVNC#131]
WinVNC.exe will generate an UltraVNC.ini file, and I don't want anyone to see it. Can I not create this file and save all the parameters to the program memory

**Comment by RudiDeVos** [comment]
This file contain all settings, including the authentication, the file is needed.
But when you are admin and the users are not, you can play with the file permissions.
Read only for admins....
VNC running as service still can read the file, normal users can't open it.
