### ISSUE TITLE
Message UNSUPPORTED OS when running winvnc.exe in WinRE 10

### ISSUE THREAD

**Issue by panreyes** [ultravnc/UltraVNC#135]
Windows 10/11 and WinPE 10/11 identify theirselves as NT 6.2 but WinRE 10/11 identifies itself as NT10.0.

When executing winvnc.exe in WinRE it displays an "Unsupported OS" message and then closes.

Just removing the check ( https://github.com/ultravnc/UltraVNC/blob/982779cecd31fc5df574bbd60a9943070418fc62/winvnc/winvnc/vncOSVersion.cpp#L83C1-L84C1 ) makes it work as expected :)

**Comment by RudiDeVos** [comment]
Do you mean that OSversion.dwMajorVersion = 10 and minorversion =0 when you run winRE
Then it would be better that we add OSversion.dwMajorVersion> 6
if (OSversion.dwMajorVersion==6 && OSversion.dwMinorVersion>=2  ||  OSversion.dwMajorVersion> 6)

**Comment by panreyes** [comment]
That might work, or maybe changing that line to:
`if ((OSversion.dwMajorVersion==6 && OSversion.dwMinorVersion>=2) || (OSversion.dwMajorVersion==10 && OS_WINPE)) OS_WIN8=true;`

In any case, I would also recommend not closing WinVNC when it detects an unknown version of Windows.

**Comment by RudiDeVos** [comment]
added

**Comment by Neustradamus** [comment]
@tobydox: For your information ^^

**Comment by tobydox** [comment]
Thanks for informing!
