### ISSUE TITLE
Upgrade to the latest zstd 1.4.9

### ISSUE THREAD

**Issue by breisig** [ultravnc/UltraVNC#14]
Update the core zstd from 1.4.5 to the latest 1.4.9 [ https://github.com/facebook/zstd ]

**Comment by Neustradamus** [comment]
@RudiDeVos: https://github.com/facebook/zstd/releases

Now it is 1.5.0.

Time to separate libs from main code too.

**Comment by RudiDeVos** [comment]
Lib upgraded to 1.5.0

**Comment by Neustradamus** [comment]
@RudiDeVos: Thanks!

**Comment by breisig** [comment]
@RudiDeVos Thanks :-)
