### ISSUE TITLE
Can you remove https://sourceforge.net/p/ultravnc/code/ ?

### ISSUE THREAD

**Issue by lwcorp** [ultravnc/UltraVNC#15]
The latest file update in https://sourceforge.net/p/ultravnc/code/ is currently from April 2020.
The latest file update from this repository is currently from December 2020.

This indicates you've stopped using SourceForge in favor of GitHub.
In that case, can you remove SourceForge's repository to avoid any confusion?

**Comment by Neustradamus** [comment]
@lwcorp: On SourceForge homepage, there is a message about the change...
- https://sourceforge.net/projects/ultravnc/

Note: There is a development branch too.

**Comment by lwcorp** [comment]
True, but it's quite small and unnoticeable.
Be that as it may, what benefit do you get from keeping an unmaintained code there? I think there should be just 1 code, notice or not. I assume all branches are here.

**Comment by RudiDeVos** [comment]
SVN code was there as reference, removed and replaced by a git that's in sync with the main github branch

**Comment by lwcorp** [comment]
> This indicates you've stopped using SourceForge in favor of GitHub. In that case, can you remove SourceForge's repository to avoid any confusion?

Thanks for eventually removing it!

**Comment by lwcorp** [comment]
> SVN code was there as reference, removed and replaced by a git that's in sync with the main github branch

Thanks for removing it!
