### ISSUE TITLE
BIN files will not download on website

### ISSUE THREAD

**Issue by rootd1337** [ultravnc/UltraVNC#187]
![image](https://github.com/ultravnc/UltraVNC/assets/159929328/56e4ddff-2919-49c5-ae4c-0b586559765f)
All antivirus disabled

OS: windows 10

**Comment by RudiDeVos** [comment]
remove the www from the name and now all seems to work again.
Don't understand why a msi download from www.uvnc.eu and a zip needs uvnc.eu

**Comment by aledog007** [comment]
Hello dear Team

The issue persists. Could you please provide a video demonstrating or a documentation how to resolve it?

OS: Windows 10

Additionally, as a note, when attempting to visit .eu domains, I am redirected to .com. Also, there isn't a "www" prefix, and it doesn't work either.

Thank you.

**Comment by RudiDeVos** [comment]
update a parameter in Jdownload module

**Comment by RudiDeVos** [comment]
Latest are here 
https://www.uvnc.eu/download/1500/
