### ISSUE TITLE
How to check if UltraVNC's port is open without receiving an error

### ISSUE THREAD

**Issue by panreyes** [ultravnc/UltraVNC#196]
I would like to check remotely if UltraVNC Viewer listener port is open without triggering any errors, like this one:
![image](https://github.com/ultravnc/UltraVNC/assets/13276823/eb22c6a0-5513-4cb3-ad5d-008433f89d84)

Is there a way to do that?

**Comment by RudiDeVos** [comment]
If it is for  checking is the pc is online and vnc is running you can use the echo port.
From 1.5.0.0 UltraVNC server has a echo udp port on the tcp vnc port.

**Comment by panreyes** [comment]
That works for winvnc, but not for vncviewer, right? In any case, I would like to avoid having 2 ports forwarded in the router.

I think I can solve it with an option that will just disable throwing the error "End of Stream", and with the "No status" option will be good enough for my case. I'll send a PR if I manage to make it good enough.

**Comment by RudiDeVos** [comment]
Uups sorry, the viewer generate that popup and require code change to fix

**Comment by panreyes** [comment]
Solved by PR https://github.com/ultravnc/UltraVNC/pull/199 ! 🥳
