### ISSUE TITLE
Bug bounty program

### ISSUE THREAD

**Issue by joejoe2010** [ultravnc/UltraVNC#2]
Hi,
have you been thinking about participating in a bug bounty program like hackerone in order to increase the security of this widely used program?
Thanks
joejoe

**Comment by RudiDeVos** [comment]
Uvnc is free. We don't have fonds for this.
Kaparsky checked our source alast year , some weak points were fix.

**Comment by joejoe2010** [comment]
Hi,
I'm aware that there's no fond for this. Bug bounty programs can also be made without offering money to those who find something.
