### ISSUE TITLE
Inquiries about connecting to multi-viewer servers while using Repeater

### ISSUE THREAD

**Issue by Marker0724** [ultravnc/UltraVNC#205]
I'm using Repeater. And I'm using server by registering with Windows service. Is there a way to attach multiple viewers to a single server? Repeater mode is using 2, and there seems to be no way to modify the -Multi command and other ini file settings. Please help.

I'm sorry for the lack of English.

**Comment by Neustradamus** [comment]
@RudiDeVos: Have you seen this ticket?

**Comment by RudiDeVos** [comment]
It's possible from application, but the service doesn't have this option, the service can only make one outgoing repeater connection

**Comment by Marker0724** [comment]
While the service was running, we verified through testing that it was possible to perform tasks using the service_run and multi commands. Thank you for your response.
