### ISSUE TITLE
Accept/Refuse prompt while Windows is locked

### ISSUE THREAD

**Issue by BartJonckers** [ultravnc/UltraVNC#22]
We've been installing UltraVNC as a service with the SecureVNC DSM plugin and MS domain logon - in combination with the Query window that automatically refuses all connections, unless Windows is at the logon screen, so that nobody can accidentally stumble into a user session without their explicit consent
![image](https://user-images.githubusercontent.com/89633608/131098753-09fffe72-265c-4d8f-92f8-e9d4b85610f5.png)

Unfortunately, the code that checks whether Windows is locked does not work properly if uvnc is running as a service...

- No user logged on : no query   -> works as expected
- User logged on and active : query with auto-reject   -> works as expected
- User logged on but session locked : query still displays in the background (invisible on login screen) and auto-rejects   -> query should not display, connection should be accepted

We've been running a custom build, that just checks for a running "LogonUI" process instead (the "login screen") - this works as expected.  Might be a nice fix for others with the same problem.

diff --git a/ultravnc/winvnc/winvnc/vncservice.cpp b/ultravnc-lock/winvnc/winvnc/vncservice.cpp
index d65c437..d9386d0 100644
--- a/ultravnc/winvnc/winvnc/vncservice.cpp
+++ b/ultravnc-lock/winvnc/winvnc/vncservice.cpp
@@ -40,6 +40,9 @@ extern HWND G_MENU_HWND;
 #include "vncmenu.h"
 #include "vnctimedmsgbox.h"
 
+#include <tlhelp32.h>
+#include <wchar.h>
+
 #include "Localization.h" // Act : add localization on messages
 
 
@@ -373,8 +376,26 @@ BOOL vncService::IsWSLocked()
 
        bool bLocked = false;
 
+        // Original code does not work if running as a service...  apparently no access to the desktop.
+        // Alternative is to check for a running LogonUI.exe (if present, system is either not logged in or locked)
+        HANDLE hSnap = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);
+
+        PROCESSENTRY32W procentry;
+        procentry.dwSize = sizeof(procentry);
+
+        if (Process32FirstW(hSnap, &procentry))
+        {
+            do
+            {
+                if (!wcsicmp(procentry.szExeFile, L"LogonUI.exe"))
+                {
+                    bLocked = true;
+                    break;
+                }
+            } while (Process32NextW(hSnap, &procentry));
+        }
 
-       HDESK hDesk;
+       /*HDESK hDesk;
        BOOL bRes;
        DWORD dwLen;
        char sName[200];
@@ -401,7 +422,7 @@ BOOL vncService::IsWSLocked()
                         bLocked = false ;
        }
        if (hDesk != NULL)
-               CloseDesktop(hDesk);
+               CloseDesktop(hDesk);*/
 
        return bLocked;
 }

**Comment by Neustradamus** [comment]
@RudiDeVos: Have you seen the @BartJonckers ticket?

**Comment by RudiDeVos** [comment]
Thanks,
I will take a look at it for net update.

**Comment by RudiDeVos** [comment]
added

**Comment by Neustradamus** [comment]
Merged commit is:
- https://github.com/ultravnc/UltraVNC/commit/a764c026cae6e4f917403259ceeb3356f1f4f5a5

**Comment by Neustradamus** [comment]
There is a request to update here:
- https://github.com/ultravnc/UltraVNC/issues/55
