### ISSUE TITLE
Wallpaper not removed with new SC_20

### ISSUE THREAD

**Issue by rvk01** [ultravnc/UltraVNC#223]
With the newer UltraVNC SC now integrated in the normal UltraVNC, the wallpaper isn't removed anymore.

There are settings in ultravnc.ini (i.e. RemoveWallpaper and Frame) which aren't used in the SC_20 mode.
So there is also no way to fix this with this newer version.

Was this an intentional change?

In UltraVNC/winvnc/winvnc/SettingsManager.cpp the complete [admin] section falls outside the SC_20.
(and the default seems to be set to transfer the wallpaper now for SC)

It would be very useful if Frame and RemoveWallpaper would be added to the SC_20.ini as possibility.
(or at least that RemoveWallpaper = true became the default again, as was the case in the previous standalone version)

**Comment by RudiDeVos** [comment]
done
