### ISSUE TITLE
Problem compiling SC_20 (missing IDR_DLL define)

### ISSUE THREAD

**Issue by rvk01** [ultravnc/UltraVNC#227]
It seems SC_20 doesn't compile anymore (or I'm doing something wrong, I'm new to VS).

Before April there were some lines in resource.h but these are removed.
The compile for SC_20 complains about that.

```
#if defined(SC_20)
  #define IDR_DLL1                        176
  #define IDR_ENCRYPTIONDLL1              177
#endif
```

> Severity	Code	Description	Project	File	Line	Suppression State	Details
> Error	C2065	'IDR_DLL1': undeclared identifier	winvnc	C:\source\UltraVNC\winvnc\loadmemory\loadDllFromMemory.cpp	28		
> Error	C2065	'IDR_ENCRYPTIONDLL1': undeclared identifier	winvnc	C:\source\UltraVNC\winvnc\loadmemory\loadDllFromMemory.cpp	55		

Also the winvnc.rc had those symbols for the ddengine.dll (and encrypt).

But they both seem to be removed in this revision from resources.h and winvnc.rc:
https://github.com/ultravnc/UltraVNC/commit/48a9c7bf99403eb5bc712d1f4f7f30a502d0ab24

**Comment by RudiDeVos** [comment]
Thanks, VS always remove that part from the rc file forgot to exclude in sourcetree

**Comment by RudiDeVos** [comment]
updated, it build, but not tested

**Comment by rvk01** [comment]
> updated, it build, but not tested

It works here (as far as I can see).
winvnc.exe for SC is 4+MB, so the SecureVNCPlugin.dsm and ddengine.dll are embedded again (previous it was 2.7MB without).
