### ISSUE TITLE
Feature Request: Disabling the filetransfer button on viewer side

### ISSUE THREAD

**Issue by Pfannaa** [ultravnc/UltraVNC#23]

**Comment by Neustradamus** [comment]
@RudiDeVos: Have you seen the @Pfannaa ticket?

**Comment by RudiDeVos** [comment]
Filetransfer is a server/viewer option.
What's the goal of being able to enable/disable the button as viewer option ?
The viewer is a desktop app, the user always can enable it back.

The server already has the option to disable it.  If you disable it at server site the viewer doesn't have the button and is unable to activate it back.

**Comment by Pfannaa** [comment]
In that case we have a rather unconventional reason for this feature request.
We have a server where our external partner companies can connect to, to support some special equipment.
In the end they launch a .vnc directly over a shell to the remote computers where they shouldn't be able to initiate any file transfer, because they could go through the servers local files.

**Comment by RudiDeVos** [comment]
I"m trying again...
Current implementation already allow to remove the filetransfer from all viewers,  using a server setting.
When the viewer connect to the server he ask if FT is supported and when not the viewer disable it.
![image](https://user-images.githubusercontent.com/71467484/132997163-c217d5a8-675c-4267-9ac0-cea9f7a88e66.png)

All viewer options are users options, if we add disable FT then the user can enable it back as a viewer doesn't have admin control like the server.

You could use another vnc flavor viewer ( tight or realvnc) , then FT is disabled as they don't support it.

**Comment by Pfannaa** [comment]
I got your point..
We just didn't want to disable FT on 400 different machines.

Does tight or real support the uvnc file format ?
I checked tigervnc and they didn't.

**Comment by RudiDeVos** [comment]
I don't think they does, FT was independent develop, FT is no part of the rfb protocol.
You need to check it, it's always possible that it's made compatible later on.

**Comment by Pfannaa** [comment]
alright, thanks a lot.
Closed
