### ISSUE TITLE
Feature: direct copy-and-paste functionality for transferring files

### ISSUE THREAD

**Issue by PatrHofmann** [ultravnc/UltraVNC#245]
UltraVNC does not support direct copy-and-paste functionality for transferring files between a host and a remote computer.

**Comment by PatrHofmann** [comment]
i see its a duplicate

**Comment by PatrHofmann** [comment]
i see its a duplicate

**Comment by Neustradamus** [comment]
@PatrHofmann: Can you try the latest version?
- https://forum.uvnc.com/viewforum.php?f=56

Thanks in advance.
