### ISSUE TITLE
Proposed patch by Peter2121 published on the forum in 2020

### ISSUE THREAD

**Issue by Neustradamus** [ultravnc/UltraVNC#25]
@RudiDeVos: Can you look the Peter2121 patch published on the forum?
- https://forum.ultravnc.net/viewtopic.php?f=5&t=36346

"Hello,
Playing with winvnc.exe, I noticed that in case of starting winvnc.exe with -install argument (to install the service) it ignores -inifile argument, so it is impossible to install the service with a custom path of ini file. Hopefully, the fix is trivial, so I propose the following patch to include in a future release"

1.5 years already.

**Comment by RudiDeVos** [comment]
done

**Comment by Neustradamus** [comment]
Merged commit is:
- https://github.com/ultravnc/UltraVNC/commit/7060d3f22fd2276e18655bbfe20bedfe2ed8580c

**Comment by Neustradamus** [comment]
@RudiDeVos: Do not forget to reply here:
- https://forum.ultravnc.net/viewtopic.php?f=5&t=36346
