### ISSUE TITLE
server cursor is not shown at noVNC client

### ISSUE THREAD

**Issue by JB-DX** [ultravnc/UltraVNC#26]
I'm using noVNC v1.3.0 beta along with UltraVNC 1.3.4.1

The server cursor  isn't shown in noVNC.

With UltraVNC-viewer it can be turned on by checking:
"Track remote cursor locally"

So it has to be done on the viewer side.
The noVNC author claims that it is a bug in unvnc, not sure if that is true.
see: https://github.com/novnc/noVNC/issues/1581

Is there a solution available? 
If not, can the server be instructed to send the cursor position?
How does the uvnc-viewer instructs the server to send it?

When doing a presentation it's annoying that our clients can's see where I'm (at the server) pointing to.

**Comment by RudiDeVos** [comment]
This is also fixed with the latest patch for TigerVNC.
test version
https://www.uvnc.eu/download/1342/winvnc_TigerCursorTest2.zip.

**Comment by Neustradamus** [comment]
@JB-DX: It is good for you?
You have not replied, please confirm.

**Comment by JB-DX** [comment]
Thanks for reminding. I did not fully understand the reply mentioning TigerVNC, so did nothing. Now I see that that the server was updated, and just tried it. And it does work well now. 
Thanks very much.

**Comment by JB-DX** [comment]
It took me a while to set up everything again for this test. Many things I already had forgotten.
I tested 1.8.0.5 and found no problems.
Thank you for your update !

**Comment by Neustradamus** [comment]
@JB-DX: Thanks for your test and confirmation :)

Note: 1.8.0.8 is now here:
- https://uvnc.eu/download/1800/UltraVNC_1808_x64_Setup.exe
- https://uvnc.eu/download/1800/UltraVNC_1808_x86_Setup.exe
- https://uvnc.eu/download/1800/UltraVNC_1808.zip
