### ISSUE TITLE
Hook mode always used if in performance mode.

### ISSUE THREAD

**Issue by eebssk1** [ultravnc/UltraVNC#3]
I'm currently run uvnc on win10.Since some wpf windows will show blank so i enabled DDE.However after i enabled performance mode it begin to use (sc)hook mode only everytime.This is annoying.I set cpu max usage to other values and then it works again.

**Comment by RudiDeVos** [comment]
What you can try, remove vnchook and schook dll's.
If they don't exist uvnc is never gonna use that method.  Hooking is a fallback method.
I will try to repeat it and check if the sethook is called by settings abreak at that spot.

**Comment by eebssk1** [comment]
I found it may not really caused by cpu cap.It's pretty random.If something already explicitly using 3d like QT-based app,firefox and other things are running,then uvnc will always(most likely) use schook,even if i close them and restart uvnc service.
The only always work method is reboot my pc and vnc in, then login and start any app,this will use DDE.
I'll test the method you said and see if it cause any issues.

**Comment by eebssk1** [comment]
@RudiDeVos  Well I think I'm basically found the problem.
If my laptop's lid is closed,uvnc failed to use ddengine because there's no monitor available and framebuffer is paused.However if you connect to uvnc before you close the lid,uvnc will continue work fine with ddengine after closing lid cause it's still using the framebuffer and windows knows this(this is guess).
I tried delete all hook library and now uvnc uses pure polling(V 1.3.1 RC),but it's more worse than not using hook cause there's a lot of new blackboxes.
RealVNC says polling should fix this but i haven't tried since it's paid software.
I think the last way to solve this is use dummy hdmi plug....
I saw the new uvnc now contain a virtual display driver,if it has rdp virtual display driver's function then it will solve this i guess?

**Comment by RudiDeVos** [comment]
The virtual display driver act as a usb monitor, not a rdp independed session.
What happen if you connect an external monitor and close the lid, does the external monitor stay active ?
Normal, your portable software has an option to configure the close lid action.

**Comment by eebssk1** [comment]
@RudiDeVos Yes windows automatically switch display to external monitor after lid is closed.
I tried set do nothing after closing lid in power setting but it's the same. The only soft way i found is disable the laptop lid acpi device in device manager,but this will make laptop screen unable to wake from sleep.

**Comment by eebssk1** [comment]
Found a trick...Reboot laptop and then vnc in will let uvnc use ddengine after log in.This is random but it works most time.Since there's no critical process running this is at least sufficient for me..
