### ISSUE TITLE
Unattended Installation does not create start menu entries

### ISSUE THREAD

**Issue by martin1563** [ultravnc/UltraVNC#30]
Environment:
- UltraVNC: 1.3.4.2, 64bit
- Operating system: Windows 10, 64bit, Version 21H2, Build 19044.1348)

I have created with the parameter "/SAVEINF" the following INF installation file:

```
[Setup]
Lang=en
Dir=C:\Program Files\uvnc bvba\UltraVNC
Group=UltraVNC
NoIcons=0
SetupType=custom
Components=ultravnc_server,ultravnc_viewer
Tasks=installservice,startservice,associate,installdriver
```

If I install the application with the following parameters the installation itself is successful but no start menu entry was created:
`UltraVNC_1_3_42_X64_Setup.exe /verysilent /norestart /restartapplications /loadinf="setup.inf"`

With a normal installation (without parameters, just double click on the setup file) the start menu entries were created.

**Comment by Neustradamus** [comment]
@RudiDeVos: Please read here.

**Comment by RudiDeVos** [comment]
Add desktopicons, it also create the startmenu
Tasks=installservice,startservice,desktopicon,associate,installdriver
onno file attached

[UltraVnc_installer_all_X64.txt](https://github.com/ultravnc/UltraVNC/files/7611760/UltraVnc_installer_all_X64.txt)

**Comment by martin1563** [comment]
Thank you very much for the hint.

Is it possible to separate the creation of desktop and start menu shortcuts?

As far as I know in a previous version was this separated (with unattended installation).

In the normal installation it is now also separated:
![startmenu_shortcuts](https://user-images.githubusercontent.com/94899084/143821313-49103227-ac41-4588-af82-3fc6e3bc1bfb.png)
![desktop_shortcuts](https://user-images.githubusercontent.com/94899084/143821335-80a6b03d-97e4-4dae-a0bb-dc3288827c63.png)
