### ISSUE TITLE
Feature Request - Add Informational Border when connected to a computer

### ISSUE THREAD

**Issue by Tythesly** [ultravnc/UltraVNC#31]
I would like to suggest adding the option to setup a colored border that goes along the edges of the screen when you are connected to a computer. If we could add customizable text to it as well would be great. As of right now we use this for remote support for our employees and when we connect to their computers a couple of... Technically challenged... People have freaked out thinking they have been hacked or something before we can open the chat window and try to communicate... but most of the time they close it right away.

**Comment by Neustradamus** [comment]
@RudiDeVos: Please read here.

**Comment by RudiDeVos** [comment]
Implemented in dev edition
https://forum.uvnc.com/viewtopic.php?p=110296#p110296

**Comment by Tythesly** [comment]
Awesome! Can't wait till its in the stable release :D
