### ISSUE TITLE
Feature Request - Ability to Add Text to Sharing Border

### ISSUE THREAD

**Issue by Tythesly** [ultravnc/UltraVNC#33]
Hey Thanks so much for adding the colored frame option for when youre connected to a computer. I would like to ask though if possible  to add the ability to add your own text to it? We would use something like "IT is currently working on this computer". The users don't know what the border actually means. And when we are working on Public computers it would be cool to have that so people actually know were doing something and not hop on and use it lol.

**Comment by RudiDeVos** [comment]
Current this can be done with a Notification ( systray) and it popup for a few seconds on connection.
Your re quest is to add the same text as OSD, like the border, only visible on the server pc.

This should be that hard of we reuse the same text from the Notify.
On the Todo

**Comment by Tythesly** [comment]
Yeah that would be perfect! That way it is a constant type of notification in case there is no user at the computer at the time :)

**Comment by RudiDeVos** [comment]
Added in 1.3.8.0
https://uvnc.com/downloads/ultravnc/149-ultravnc-1-3-8-0.html
