### ISSUE TITLE
https://uvnc.com/ reporting NET::ERR_CERT_DATE_INVALID

### ISSUE THREAD

**Issue by temannin** [ultravnc/UltraVNC#34]
With the new year, the certificate for http://uvnc.com has expired. 

![image](https://user-images.githubusercontent.com/24688933/147841680-c7293052-98a6-4973-b947-bf41d47c2c45.png)

**Comment by temannin** [comment]
This seems to have been resolved. Closing.

**Comment by Neustradamus** [comment]
@temannin: Thanks for your report, @RudiDeVos has solved it.

And Happy New Year ^^
