### ISSUE TITLE
Settings more similar to MP4 h264 encoding...

### ISSUE THREAD

**Issue by juanpc2018** [ultravnc/UltraVNC#36]
All VNC have weird settings,
seems VNC is Not as optimized as RDP.
RDP video is more fluid, playing a YouTube video FullHD FullScreen..
problem with Apple Remote Desktop is that is a closed environment, Not compatible with Linux or Windows RDP.
Apple also has standard VNC support.
Microsoft has an Apple to Windows RDP App for OSX.

For example:
1x PC has 2 Networks
100Mbps for Internet.
1GbE for VNC "Not Jumbo".

i play a YouTube Video,
100Mbps Network load is very low.
i see the video using VNC,
1GbE Network load is near 500Mbps.

Most YT videos are encoded with .mkv or .mp4 at 8Mbps,
Internet has Bursts of 100Mbps.
Not a constant stream.

example:
a Sony camera with XAVC h.264 codec has 50Mbps or 100Mbps for HighQuality and WAV LPCM Audio., 
looks Ok, at 24fps or 30fps, Not enough for 120fps or 240fps.
the higher the frame rate the lower the image quality at same bitrate.
.jpg vs. 50Mbps h.264 there is a drop in quality, usually in the shadows.

WindowsRDP Server to Linux KRDC
LAN setting.
has 200Mbps Fullscreen + Audio.
 
500Mbps VNC would be ok if were fluid at 60fps, 
but looks like skips frames in some areas, hiccup, 
frame-buffer has tearing on large moving objects,
latency seems high...
No audio,
seems like VNC does Not have DMA "Direct Memory Access", or something is wrong with VNC.

i´m using AMD RAMDrive for 4GB Temp folder. in Windows Machine..
older computers "2010" require that...

P.D.
in Windows8.1 requires Run as Administrator,
when Windows8.1 is Not in Test Mode.
i wont buy W10 don´t insist.

Anyway... 
MP4 encoding settings are easier to understand & more advanced for optimization,
like Handbrake.fr x264 or similar h.264 algorithms... 
like OBS
h.265 requires latest gen. video card with HW decoder, or CPU usage will be high... some players have crash.

YUV color encoding "fake RGB"
709 color space
RGB true color encoding.
4:2:2
4:4:2
4:4:4
Codec: ffmpeg has many, but Not all.

CFR Constant Frame Rate.
CBR Constant Bit Rate
VBR Variable Bit Rate
VFR Variable Frame Rate.
mBR minimum Bit Rate
MBR Max Bit Rate
ABR Average Bit Rate.

Frame Rate: 3, 6, 12, 15, 24, 30, 48, 60, 120, 144, 
custom: 23.976, 29.97, etc... 
Same as Source.

HW accelerated encoding, 
etc...
Presets...

**Comment by RudiDeVos** [comment]
VNC is used for 54k connections to fast 10 gb LAN.
This makes it very hard to find the correct parameters that works in all cases.

VNC has direct memory access 
- <=win7  using the mirror driver
- win10 using the ddengine
In both cases, we have access and now what changed

There is no direct memory access on win8, MS didn't provided the functions to be able todo it.
You need to copy the ramebuffer and scan for changes... slow as hell.

The current video encoder use YUV with hardware accelerated (CPU) jpeg.
On windows 10 this can deliver 60fps for HD

VNC use a viewer pull, the viewer request frames, not the  fastest way for pure video but needed if you want the mouse and keyboard to be in sync with the screen.
