### ISSUE TITLE
Donation link and email on website broken

### ISSUE THREAD

**Issue by user8446** [ultravnc/UltraVNC#38]
Hello,

In trying to donate to the project, I found the link on the [website](https://uvnc.com/) homepage just links back to the homepage. I then sent an email listed on the homepage ( uvnc@skynet.be ) regarding this and the email bounced back.
The undeliverable message says info@uvnc.com doesn't exist so apparently uvnc@skynet.be just forwarded to info@uvnc.com.

Whoever handles the website, please update the email and donation links. Thank you!

Edit: The donation link does work on the download page, so it's the homepage and email that needs corrected

**Comment by RudiDeVos** [comment]
Donation fixed.
Mail addresses get spammed in months and are no longer workable,  the fastest way is to use the forum.

**Comment by user8446** [comment]
Thank you
