### ISSUE TITLE
Can reverse connection survive logoff?

### ISSUE THREAD

**Issue by LamerDrv** [ultravnc/UltraVNC#39]
Hi!
I can create reverse connection. But connection drop when I do logoff on comp with vncserver.
Can vncserver in service mode keeps reverse connection during logoff ?
In "UltraVLC Server Property Page" window I see "Reverse connection" section. But what options I must set for service keeps reverse connect (or make reverse reconnect) on windows logon screen?

**Comment by Neustradamus** [comment]
@RudiDeVos: Can you look this ticket?

**Comment by RudiDeVos** [comment]
Yes
You need to run as service and use the service_commandline
![image](https://user-images.githubusercontent.com/71467484/156883355-dd565a55-dcb8-47ca-beb4-ed6c44af6d1e.png)
-autoreconnect -connect your_ip_address_of the viewer

Then on each disconnect, the server initiate a new connection.
