### ISSUE TITLE
Accept server without authentification

### ISSUE THREAD

**Issue by casperklein** [ultravnc/UltraVNC#40]
Hello,

I've updated to the latest vncviewer.exe. Now I get this warning, when connecting to my (passwordless) VNC server:

![message](https://user-images.githubusercontent.com/646444/144070663-889fb317-40e5-461b-913f-a9695398f6e4.png)

Is there a CLI switch or something to suppress this warning?

**Comment by Neustradamus** [comment]
@RudiDeVos: Can you look this ticket?

**Comment by RudiDeVos** [comment]
Can be disabled in 1.3.8.0.
see https://uvnc.com/downloads/ultravnc/149-ultravnc-1-3-8-0.html

**Comment by casperklein** [comment]
Thank you for implementing this. There is no CLI option for that, or do I miss something?

**Comment by RudiDeVos** [comment]
commandline AllowUntrustedServers
