### ISSUE TITLE
When using -autoreconnect in winvnc.exe, the listening viewer will ask for a password

### ISSUE THREAD

**Issue by panreyes** [ultravnc/UltraVNC#44]
Hello!

With current UltraVNC Server, running as elevated application or service, if I use the -autoreconnect parameter, the listening viewer asks for a password (which is already in the INI file).
- This works: -connect xx.xx.xx.xx:5500
- This does not work: -autoreconnect -connect xx.xx.xx.xx:5500

This is what is different in the log when using autoreconnect:
`Entered InitAuthenticate  
winvnc\vncserver.cpp : client x.x.x.x verifiedHost 0 prior to adjustment  
winvnc\vncserver.cpp : client x.x.x.x verifiedHost 0 after adjustment password authentication  
`

Update: This only occurs if there is a password set (which is in the server INI but also in the viewer INI, afaik). 
Without the password it works with -autoreconnect too.

**Comment by Neustradamus** [comment]
@RudiDeVos: Have you seen this issue?

**Comment by Neustradamus** [comment]
@RudiDeVos: Can you look?

**Comment by Neustradamus** [comment]
@RudiDeVos: Can you look?

**Comment by Neustradamus** [comment]
@RudiDeVos: Have you seen this ticket?

**Comment by RudiDeVos** [comment]
Server Options
Is this on ?
[_] Authentication required for server initiated connections

**Comment by panreyes** [comment]
Yes, it is set.

**Comment by Neustradamus** [comment]
@panreyes: Do not forget it!

**Comment by panreyes** [comment]
Sorry. I have tried to reproduce it, but I couldn't.

Please feel free to close this issue. I will update it if it happens again
