### ISSUE TITLE
not support visual studio libjpeg-turbo-win

### ISSUE THREAD

**Issue by introspection3** [ultravnc/UltraVNC#49]
not support visual studio  libjpeg-turbo-win

**Comment by introspection3** [comment]
error	MSB8066	“simd\i386\jccolor-avx2.asm;simd\i386\jccolor-mmx.asm;simd\i386\jccolor-sse2.asm;simd\i386\jcgray-avx2.asm;simd\i386\jcgray-mmx.asm;simd\i386\jcgray-sse2.asm;simd\i386\jchuff-sse2.asm;simd\i386\jcphuff-sse2.asm;simd\i386\jcsample-avx2.asm;simd\i386\jcsample-mmx.asm;simd\i386\jcsample-sse2.asm;simd\i386\jdcolor-avx2.asm;simd\i386\jdcolor-mmx.asm;simd\i386\jdcolor-sse2.asm;simd\i386\jdmerge-avx2.asm;simd\i386\jdmerge-mmx.asm;simd\i386\jdmerge-sse2.asm;simd\i386\jdsample-avx2.asm;simd\i386\jdsample-mmx.asm;simd\i386\jdsample-sse2.asm;simd\i386\jfdctflt-3dn.asm;simd\i386\jfdctflt-sse.asm;simd\i386\jfdctfst-mmx.asm;simd\i386\jfdctfst-sse2.asm;simd\i386\jfdctint-avx2.asm;simd\i386\jfdctint-mmx.asm;simd\i386\jfdctint-sse2.asm;simd\i386\jidctflt-3dn.asm;simd\i386\jidctflt-sse.asm;simd\i386\jidctflt-sse2.asm;simd\i386\jidctfst-mmx.asm;simd\i386\jidctfst-sse2.asm;simd\i386\jidctint-avx2.asm;simd\i386\jidctint-mmx.asm;simd\i386\jidctint-sse2.asm;simd\i386\jidctred-mmx.asm;simd\i386\jidctred-sse2.asm;simd\i386\jquant-3dn.asm;simd\i386\jquant-mmx.asm;simd\i386\jquant-sse.asm;simd\i386\jquantf-sse2.asm;simd\i386\jquanti-avx2.asm;simd\i386\jquanti-sse2.asm;simd\i386\jsimdcpu.asm” code  9009。	libjpeg-turbo-win	D:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets	245

**Comment by RudiDeVos** [comment]
We use nasm
https://www.nasm.us/
After installing make sure nasm is in your path

**Comment by Neustradamus** [comment]
@introspection3: It has been solved?

**Comment by Neustradamus** [comment]
@introspection3: Have you looked:
- https://github.com/libjpeg-turbo/libjpeg-turbo/blob/main/BUILDING.md

**Comment by Neustradamus** [comment]
@introspection3: It has been solved?

**Comment by Neustradamus** [comment]
@introspection3: It is possible to have an answer from you?
