### ISSUE TITLE
Possible Security hole in UltraVNC server

### ISSUE THREAD

**Issue by mgpetrel** [ultravnc/UltraVNC#50]
I have UltraVNC server installed in Windows 10 machines.
Once every 2 months or so the machines receive some kind of external attack which results in the incoming connection window (Accept/Reject) popping out in the PC under attack.

![Incomming2](https://user-images.githubusercontent.com/89139598/179313153-0bc5a75a-91e6-40dd-bc24-d3990f92eea3.jpg)

I'm using the encryption plugin, and --so far-- I can say that even if the user "Accepts" the incoming connection, such connection fails and the targeted PC stays safe --so far. 

The incoming connection re-appears every 2 minutes and repeats itself for a number of times (100 to 200). I interpret such periodicity and persistence as an indication of an automated process behind the attacks. 

As expected, the attacks leave a trail in the **mslogon.log** file, which looks like this:

![MSLOGON2](https://user-images.githubusercontent.com/89139598/179318520-7a02e5f8-3d47-4d00-8d2e-a405231dfe44.PNG)

**Now, this is the strangest part:**
1. If a legit incoming connection with the right encryption key fails the password (whether accidentally or purposely for-testing), or
2. If a test-connection lacks the right client-side encryption key...
 
...the result of both situations described above is:  

**A.** The mslogon.log file logs **two** lines per attempt (not just  one as the hacking attempt):
````
    Connection received from <remote IP>
    Invalid attempt from client <remote IP>
````
**B.** The incoming connection window (Accept/Reject) never pops-out in the target computer; the user of the PC does not get notice that someone remote is trying to connect to his/her computer.

This leads me to think that there must be a branch in the source code that is capable of triggering the _incomming connection window_ without having the right password/key. This branch apparently cannot be executed _legally_ (using the UltraVNC client) but can be executed otherwise.

It'd be nice to know if someone has experienced this issue, it would be nicer if an expert developer could find and fix this bug.

Thanks for reading.
Matu

**Comment by Neustradamus** [comment]
@RudiDeVos: Can you look?

**Comment by RudiDeVos** [comment]
What you see is the blacklisting mechanism.

If the same ip adress is refused multiple times, it's blacklisted.
A blacklisten ip address need to wait x minutes multiplied by the number of wrong connections.

In that case no accept/reject is shown because the ip  never get to that part.
The first check is the blacklist.

**Comment by mgpetrel** [comment]
> In that case no accept/reject is shown because the connection never reach that code part.

Thanks for looking into this!

But **I do see** the accept/reject window of each "invalid attempt" shown in the _mslogon.log_. In fact, the annoyance of the accept/reject window reappearance lead me to look into the mslogon file.

**Comment by RudiDeVos** [comment]
The steps are
1) Blacklist  
2) Accept/Reject
3) Authentication

1) Blacklist:  hacker get refused, please try again later.
2) Unless you accept, a hacker can't check if he enter the correct password.  He get back connection was refused.
3) return wrong password

Normal you get 3 accept/rejects then the blacklist mechanism add timeouts.
Yes you will see some accept/reject boxes.

**Comment by mgpetrel** [comment]
> The steps are
> 
> 1. Blacklist
> 2. Accept/Reject
> 3. Authentication
> 
> 1- Blacklist: hacker get refused, please try again later. 
> 2- Unless you accept, a hacker can't check if he enter the correct password.

Sorry to insist, but how can 1.Blacklist come before 3.Authentication? On which base is hacker blacklisted then?
Besides, when trying to reproduce this, I'm not able to trigger the Accept/Reject window unless I enter the right password/have right encryption key (using viewer.exe).

**Comment by RudiDeVos** [comment]
viewer connect
1° add ip to blacklist  ( all connections are added to the blacklist)
2° If ip in blacklist and timout is not passed -> refuse
3° Check the rfb protocol 
3.7<= Ask_Permission-> activate encryption -> verify passwd  -> succeess -> remove ip from blackist ( old protocol http://www.uvnc.eu/download/102/)
3.8 ->activate encryption ->ask permission->check passwd -> succeess -> remove ip from blackist  1.0.96->1.3.8.1

The vncserver is compatible with rfb 3.3-3.8
Using 3.8 the accept/reject is don after encyption  in the old version this was before encryption.

**Comment by Neustradamus** [comment]
@mgpetrel: Have you seen the last @RudiDeVos comment?
It is clear?

**Comment by Neustradamus** [comment]
@mgpetrel: It is good?
Can be closed?

**Comment by mgpetrel** [comment]
Sorry, yes it can.
