### ISSUE TITLE
MSI installer parameters

### ISSUE THREAD

**Issue by 0xoffsec** [ultravnc/UltraVNC#52]
Hey all,

I have been trying to find the params for the MSI installer, but no success. So far only the EXE ones can be found and are working.
I also tried using the params in the PROPERTY table of the MSI package, but they do not work as well.
Does anyone know the solution/params?

Thank you :)

PS: I posted in the forum but my post has not been approved yet, hence why I opened this issue.

**Comment by Neustradamus** [comment]
@RudiDeVos: Can you look?

**Comment by 0xoffsec** [comment]
Is there any update @Neustradamus ?

**Comment by Neustradamus** [comment]
@0xoffsec: Have you tried last UltraVNC version?

**Comment by Neustradamus** [comment]
@0xoffsec: What is the status with the latest stable/dev build?
1.4.3.1: https://forum.uvnc.com/viewtopic.php?t=37831
1.4.3.3-dev: https://forum.uvnc.com/viewtopic.php?t=37855

**Comment by 0xoffsec** [comment]
oh hey, didnt see the notification. Will update you when im home

**Comment by Neustradamus** [comment]
@0xoffsec: 1.4.3.4-dev: https://forum.uvnc.com/viewtopic.php?t=37863

**Comment by 0xoffsec** [comment]
@Neustradamus the problem i had with the MSI (UltraVnc_1381_x64.msi) installer is that it didnt accept properties i.e. when you do: PROPERTY="viewer" it would install the whole server+viewer ("full") so i used the EXE installer instead.
The installer parameters (for the msi) are not documented like the exe due to people using the latter than the former. not even in the official docs.

When i have time i will test the newest version and get back to you.

**Comment by RudiDeVos** [comment]
extracted from msi
msiexec /lp! <msi_property_logfile> /i <msi_name>

Property(S): VIEWER = 1
Property(S): SERVER = 1
Property(S): SERVICE = 1

**Comment by RudiDeVos** [comment]
Update, replaced checkbox with radio button.... damm msi bug
Test msi
https://www.uvnc.eu/download/1400/UltraVnc_1434_dev_x86.msi
https://www.uvnc.eu/download/1400/UltraVnc_1434-dev_X64.msi

commandline 
SERVERVIEWER
1 server
2 viewer
3 server +viewer
SERVICE
1 install
2 not install

**Comment by 0xoffsec** [comment]
link are broken 404 .-.

**Comment by RudiDeVos** [comment]
uups it's subfolder 1430
Test msi
https://www.uvnc.eu/download/1430/UltraVnc_1434_dev_x86.msi
https://www.uvnc.eu/download/1430/UltraVnc_1434-dev_X64.msi

**Comment by Neustradamus** [comment]
@0xoffsec: Have you tested it?

**Comment by Neustradamus** [comment]
@0xoffsec: Have you tested 1.4.3.4-dev .msi build files?

**Comment by Neustradamus** [comment]
@0xoffsec: 1.4.3.5 has been released!
- https://forum.uvnc.com/viewforum.php?f=56
