### ISSUE TITLE
Query on incoming connection

### ISSUE THREAD

**Issue by joksik** [ultravnc/UltraVNC#54]
the ip address appears during an incoming connection it's good for security but can you also add the option to display also the computer name in addition to the ip address?.
the point is that the ip address does not say much to the user, but our computers have surnames as their names, so users could know who is trying to establish a connection if also computer hostname will be displayed.

**Comment by RudiDeVos** [comment]
accepted as feature request

**Comment by joksik** [comment]
Thank you. If there is such a need, I can test this functionality after introducing it in the dev channel

**Comment by RudiDeVos** [comment]
done
1.3.9 dev 5

**Comment by Neustradamus** [comment]
@joksik: Have you tested 1.4.0.x build?
- https://forum.uvnc.com/viewtopic.php?t=37695

**Comment by Neustradamus** [comment]
@joksik: Recall: Have you tested 1.4.0.x build?
- https://forum.uvnc.com/viewtopic.php?t=37695

**Comment by Neustradamus** [comment]
@joksik: Have you tested 1.4.2.x build?
The ticket can be closed?

**Comment by Neustradamus** [comment]
@joksik: It can be closed?

cc: @RudiDeVos.

**Comment by Neustradamus** [comment]
@joksik: What is the status with the latest stable/dev build?
1.4.3.1: https://forum.uvnc.com/viewtopic.php?t=37831
1.4.3.3-dev: https://forum.uvnc.com/viewtopic.php?t=37855
