### ISSUE TITLE
uvncbvba.UltraVnc version 1.3.8.2

### ISSUE THREAD

**Issue by syui** [ultravnc/UltraVNC#61]
https://github.com/microsoft/winget-pkgs/tree/master/manifests/u/uvncbvba/UltraVnc

It seems that `uvnc.com` can only download up to 1.3.8.1, but `uvnc.eu` can.
Has 1.3.8.2 been released?

**Comment by Neustradamus** [comment]
@syui: You can see here:
- https://forum.uvnc.com/viewtopic.php?t=37597

Currently there is a 1.3.9 dev builds:
- https://forum.uvnc.com/viewforum.php?f=86

**Comment by RudiDeVos** [comment]
1.3.8.2 was not released, it contain some bugs.
For testing it's uploaded to the ftp server. To avoid confusing, removed the 103.8.2 folder.

**Comment by syui** [comment]
Thank you very much.
https://github.com/microsoft/winget-pkgs/pull/87767
