### ISSUE TITLE
Can't change resolution in UltraVNC Server 1.3.8.1 on Windows 11

### ISSUE THREAD

**Issue by bhall7** [ultravnc/UltraVNC#62]
Hi,

I have UltraVNC 1.3.8.1 server running on both a Windows 10 Pro PC and on a Windows 11 Pro PC. I'm using VNC Viewer (free client by RealVNC for both Mac and Windows).

While in an active session, I can change the screen resolution on the Windows 10 server machine (currently set to 1600 x 900), but whenever I try to change the resolution on the Windows 11 server machine, it always reverts back to 1024 x 768. I really need a larger screen resolution on the Windows 11 machine so that I can see all of my program windows.

Why would I be able to change resolution on the Windows 10 UVNC server but not on the Windows 11 UVNC server? I re-installed UltraVNC server running as Administrator, and made sure to check to include installation of the virtual display adapter, but for whatever reason, the Windows 11 machine is stuck at 1024 x 768 resolution.

Any suggestions would be greatly appreciated. 

Thanks in advance!

**Comment by bhall7** [comment]
Anyone?

**Comment by RudiDeVos** [comment]
We can't repeat this on windows 11, winvnc running as app.
retesting as service
It also works.

you change the screen settinngs.
Then you get the timer to confirm that the resolution is OK, press ok and screen stay on w10 and w11

**Comment by bhall7** [comment]
Have you tried to replicate the issue while running UVNC Server on a headless Windows 11 machine? 

Here's a screen capture of what happens while trying to change resolution on UVNC Server on Windows 11 running headless: https://www.youtube.com/watch?v=gBcyG517Er4

**Comment by RudiDeVos** [comment]
Didn't tested Headless.
The problem is actual
**"Running vnc on a headless windows11 server, the screen resolution is stuck to the 1024x768 default setting."**

1.3.8 have the virtual display driver implemented, but it's controled by the ultravnc viewer.

Using this setting you get one display
![image](https://user-images.githubusercontent.com/71467484/200910255-41ea0889-f3b2-4a00-bc69-a5f8e578da97.png)
or
This for 2 displays, one can't be changed, but the second can have a custom resolution.
![image](https://user-images.githubusercontent.com/71467484/200910693-7c2c82f2-7f7e-498c-92d0-184f9140af58.png)

Once activated, you can also connect with another viewer, but the UltraVnc viewer is the only one who can activate it.

**Comment by bhall7** [comment]
Thanks for the reply. I'm using a Mac, so I'm using the VNC Viewer (free client by RealVNC for both Mac and Windows). I was able to connect using the UVNC client from another Windows machine, and it worked as anticipated. However, when I tried to connect with VNC Viewer from my Mac, it still does not allow me to change the resolution.

I ended up buying a DisplayPort "Dummy/Ghost Display Adapter" for like $7 on Amazon, that will hopefully trick the headless machine into thinking it has a display attached and allow the virtual adapter to work on Windows 11 in resolutions besides 1024 x 768.

**Comment by bhall7** [comment]
I purchased this virtual display adapter (https://www.amazon.com/gp/product/B071CGCTMY) for like $7, which then enabled me to change the resolution to anything I needed for my application. Would be nice to have a functioning software virtual display working in Windows 11 Pro, but for now, the hardware virtual display adapter solved it.

**Comment by Neustradamus** [comment]
@bhall7: Can you test with 1.4.2.2-dev build with and without your adapter?
- https://forum.uvnc.com/viewtopic.php?t=37794

**Comment by Neustradamus** [comment]
@bhall7: Can you test with the latest UltraVNC version?

**Comment by Neustradamus** [comment]
@bhall7: Can you test with the latest UltraVNC version?

**Comment by bhall7** [comment]
@Neustradamus , apologies, I no longer use UltraVNC, and I'm unable to test.

**Comment by Neustradamus** [comment]
@bhall7: Impossible to check the latest UltraVNC version?

Thanks in advance.

**Comment by Neustradamus** [comment]
@bhall7: Can you try the latest version?
- https://forum.uvnc.com/viewforum.php?f=56

Thanks in advance.

**Comment by bhall7** [comment]
I no longer use UltraVNC and I'm unable to test.

**Comment by Neustradamus** [comment]
@bhall7: It is not possible to install again to verify?
A perfect feedback will be good...
