### ISSUE TITLE
Cannot compile file

### ISSUE THREAD

**Issue by fortuner69926** [ultravnc/UltraVNC#66]
Hi. I had tried all VS 2015, 2017, 2019, 2022. But all of them can build file exe.
It often show error: no file afxres.h
after I deleted the line which include afxres.h, it tell me that need toolkit v1.42 in 2017 or 1.43. but I cannot install that toolkit in that VS version. I tried VS 2022, but it tell me that  RC2144	PRIMARY LANGUAGE ID not a number	winvnc, file not found language, IDB red, ...
Can you make a detail instruction to build file please? thanks you very much

**Comment by KazukiOhno** [comment]
Hello, I use VS 2019 Community. I had same error. But after installing v142 C++ MFC. I could resolve the issue. I heard MFC has afxres.h. Thanks,
