### ISSUE TITLE
Logging rework

### ISSUE THREAD

**Issue by msilveirabr** [ultravnc/UltraVNC#70]
My usecase might be interesting for a lot of people monitoring VNC activity logs:
Examples:
RDP Gateway where users connect to the intranet, hostname is RDPGW01
Let's say 5 users connected to the RDP gateway have to share a common VNC screen, all connected using MSLogon.
I know all usernames of the connected users.
But who disconnected first? last?

I have a zabbix template for VNC monitoring, where I preprocess client username and hostname with problem auto resolve expressions, currently relying on client hostname ONLY. But when 2 users connect to the same machine, from the same origin host, the zabbix problem will not autosolve, because username is missing in disconnection log messages:
```
06/02/2023 21:31:39	Connection received from 2019CORE using livreti.vnc account
06/02/2023 21:31:52	Client 2019CORE disconnected
```

After playing around the source code, I imagine this is not as simple as exposing an extra extern char ClientUsername[256], etc...

I'm not a developer, but I know how to read most source code languages, except from some OOP Languages :rofl: 

Any hints in case this is possible without messing too much around the code?

**Comment by RudiDeVos** [comment]
Thanks, will check it

**Comment by msilveirabr** [comment]
I'm just about to make a PR with this, just found a way to do it.

**Comment by msilveirabr** [comment]
Just created new PR with huge rework, where I did my best effort to bring current source to a better logging logic. :wink: 

Password Authentication, current state:
```
8/2/2023 17:46   Connection received from 2019CORE
8/2/2023 17:46   Invalid attempt from client 2019CORE
8/2/2023 17:47   Connection received from 2019CORE
8/2/2023 17:47   Connection received from 2019CORE
8/2/2023 17:47   Client 2019CORE disconnected
8/2/2023 17:47   Connection received from 2019CORE
8/2/2023 17:47   Connection received from 2019CORE
8/2/2023 17:48   Client 2019CORE disconnected
8/2/2023 17:48   Connection received from 2019CORE
8/2/2023 17:48   Connection received from 2019CORE
8/2/2023 17:49   Client 2019CORE disconnected
```
Password Authentication, new PR:
```
08/02/2023 18:19:52     Connection received from 2019CORE
08/02/2023 18:19:57     Password authentication accepted from 2019CORE (Interactive) (ID:1)
08/02/2023 18:20:20     Client 2019CORE disconnected (Interactive) (ID:1)
08/02/2023 18:20:23     Connection received from 2019CORE
08/02/2023 18:20:28     Password authentication accepted from 2019CORE (Interactive) (ID:1)
08/02/2023 18:20:52     Client 2019CORE disconnected (Interactive) (ID:1)
08/02/2023 18:20:56     Connection received from 2019CORE
08/02/2023 18:21:02     Password authentication accepted from 2019CORE (Interactive) (ID:1)
08/02/2023 18:21:07     Client 2019CORE disconnected (Interactive) (ID:1)
08/02/2023 18:21:32     Connection received from 2019CORE
08/02/2023 18:21:33     Invalid attempt from client 2019CORE
08/02/2023 18:21:48     Connection received from 2019CORE
08/02/2023 18:21:52     Password authentication accepted from 2019CORE (Interactive) (ID:1)
08/02/2023 18:22:00     Connection received from 2019CORE
08/02/2023 18:22:03     Password authentication accepted from 2019CORE (ViewOnly) (ID:2)
08/02/2023 18:22:08     Client 2019CORE disconnected (ViewOnly) (ID:2)
08/02/2023 18:22:09     Client 2019CORE disconnected (Interactive) (ID:1)
```

New MSLogon, current state:
```
3/2/2023 20:52   Invalid attempt from client WINNOME-E6L6FSO
3/2/2023 20:53   Connection received from WINNOME-E6L6FSO
03/02/2023 20:53:33  Invalid attempt (not authenticated) from client WINNOME-E6L6FSO using user@domain account
3/2/2023 20:53   Invalid attempt from client WINNOME-E6L6FSO
3/2/2023 23:41   Connection received from WINNOME-E6L6FSO
03/02/2023 23:41:37  Invalid attempt (not authenticated) from client WINNOME-E6L6FSO using wronguser account
3/2/2023 23:41   Invalid attempt from client WINNOME-E6L6FSO
3/2/2023 23:42   Connection received from WINNOME-E6L6FSO
03/02/2023 23:42:30  Invalid attempt (not authenticated) from client WINNOME-E6L6FSO using nouser account
3/2/2023 23:42   Invalid attempt from client WINNOME-E6L6FSO
3/2/2023 23:49   Connection received from WINNOME-E6L6FSO
03/02/2023 23:50:07  Connection received from WINNOME-E6L6FSO using myuser.vnc account
3/2/2023 23:50   Connection received from WINNOME-E6L6FSO
3/2/2023 23:50   Client WINNOME-E6L6FSO disconnected
3/2/2023 23:50   Connection received from WINNOME-E6L6FSO
```

New MSLogon, new PR:
```
08/02/2023 18:28:43     Connection received from 2019CORE
08/02/2023 18:28:59     MSLogon authentication refused from 2019CORE using wrongcredentials account (not authenticated)
08/02/2023 18:28:59     Invalid attempt from client 2019CORE
08/02/2023 18:29:18     Connection received from 2019CORE
08/02/2023 18:29:48     Invalid attempt from client 2019CORE
08/02/2023 18:30:13     Connection received from 2019CORE
08/02/2023 18:30:34     MSLogon authentication refused from 2019CORE using myuser.novnc account (not authorized)
08/02/2023 18:30:34     Invalid attempt from client 2019CORE
08/02/2023 18:30:40     Connection received from 2019CORE
08/02/2023 18:30:45     MSLogon authentication accepted from 2019CORE using myuser.vnc account (Interactive)
08/02/2023 18:30:52     Client 2019CORE using myuser.vnc account disconnected (Interactive) (ID:1)
08/02/2023 18:30:56     Connection received from 2019CORE
08/02/2023 18:31:05     MSLogon authentication  accepted from 2019CORE using myuser.vnc2 account (ViewOnly)
08/02/2023 18:31:11     Client 2019CORE using myuser.vnc2 account disconnected (ViewOnly) (ID:1)
```

New MSLogon, new PR, concurrent sessions from same origin:
```
08/02/2023 18:31:14     Connection received from 2019CORE
08/02/2023 18:31:19     MSLogon authentication accepted from 2019CORE using myuser.vnc account (Interactive)
08/02/2023 18:31:24     Connection received from 2019CORE
08/02/2023 18:31:30     MSLogon authentication  accepted from 2019CORE using myuser.vnc2 account (ViewOnly)
08/02/2023 18:32:11     Client 2019CORE using myuser.vnc2 account disconnected (ViewOnly) (ID:2)
08/02/2023 18:32:12     Client 2019CORE using myuser.vnc account disconnected (Interactive) (ID:1)
```

And all the changes work exactly the same in Windows Event Log.

I wish I had the knowledge to:
- Add ConnectionId to vncSPP to log this: "MSLogon authentication accepted from 2019CORE using myuser.vnc account (Interactive) (ID:1)"
- Add username/Id into Client List ( to Kill or Chat with )
- Bring DomainName / LOCAL to use user@domain / user@LOCALHOST ( AFAIK the MSLogon code supports this? )

But I guess this is my limit on this C/C++ adventure. My main goal is complete, I can now correlate login/logoff using HOST/SessionId and HOST/username

Hoping this gets into 1.4.07 release, OR a -newlog build if possible :wink:

I know this will probably break regex for current users log monitoring, that's why I gently ask for an alternative signed release if possible.

**Comment by RudiDeVos** [comment]
merged but found some errors. making corrections

void LOGEXIT(char *machine, char *user, vncClientId *clientId, bool *isinteractive) < not correct
void LOGEXIT(char *machine, char *user, int clientId, bool isinteractive)

You need to pass the value and not the pointer.
WIth a char you pass the pointer of the array, not with a value.

**Comment by msilveirabr** [comment]
> merged but found some errors.
> 
> void LOGEXIT(char *machine, char *user, vncClientId *clientId, bool *isinteractive) < not correct void LOGEXIT(char *machine, char *user, int clientId, bool isinteractive)
> 
> You need to pass the value and not the pointer. WIth a char you pass the pointer of the array, not with a value.

Well, as I stated before, I'm not a skilled C/C++ programmer :)
For some reason, I had mixed results in my tests, leading me to pass a pointer to both bool and int ( TBH, I knew that was not correct according to C standards ).
I'm just happy to see my code merged :wink:
