### ISSUE TITLE
The mouse is unclickable on a full screen application

### ISSUE THREAD

**Issue by BitterRose** [ultravnc/UltraVNC#73]
I have installed the latest version of UltraVNC and I have a problem with the full screen application installed on the Remote Machine. **It can only be clicked on the desktop, but when I launched a special full screen application, it did not work**. I checked several VNC programs and they all have the same problem. The local mouse interacts with the remote cursor but does not click. Radmin is the only one that works.
I have a similar situation on a second computer with a different full screen application.
My settings should be fine as I tested the exact same ones on another device with a full screen app and there was no problem.
Where could be the problem?

Remote machines - Windows 10
Local machine - Windows 10

**Comment by RudiDeVos** [comment]
Mouse clicks are blocked if the receving app has a higher security level as the sending app.
Try run winvnc.exe as admin or service 
Temp disable UAC to verify if it's a real UAC problem.

SendInput: This function is subject to UIPI. Applications are permitted to inject input only into applications that are at an equal or lesser integrity level.

**Comment by BitterRose** [comment]
Running as admin helped, thank you.

**Comment by Neustradamus** [comment]
@BitterRose: It has been solved? It can be closed?

**Comment by BitterRose** [comment]
Yes, problem solved
