### ISSUE TITLE
When winvnc is installed with a service name other than uvnc_service, it cannot be started normally in service mode

### ISSUE THREAD

**Issue by vincentddman** [ultravnc/UltraVNC#75]
I use version 1.4.0.6 of ultravnc. When I start the service after installing the service through the following command (.\winvnc.exe install "test"), the service is displayed as application and cannot pass UAC normally.
![image](https://user-images.githubusercontent.com/16111929/224587988-6fa5db0e-9cc9-455c-a43f-7635770b1ee1.png)
![image](https://user-images.githubusercontent.com/16111929/224588185-d980051b-d4b2-4d8b-9901-7e0db896cc17.png)
![image](https://user-images.githubusercontent.com/16111929/224588076-b2a54dc4-c0ba-4f11-bc2e-5f8fb43a1ac1.png)
![image](https://user-images.githubusercontent.com/16111929/224590500-e86c1934-50e3-4c4f-bc51-59438cba9f51.png)

Remark:
1. In the local service, if uvnc_service is not included, it will be abnormal, and if uvnc_service is included, it will be normal, but this is unreasonable.
2. I tried to install version 1.3.8.1 without this problem, so I tried to check the git change set and found that the following code changes may cause this situation.
![image](https://user-images.githubusercontent.com/16111929/224590911-80db5a04-7df8-43ce-bd23-859973802b89.png)
![image](https://user-images.githubusercontent.com/16111929/224590944-d3638fbb-cc2f-47a6-9d31-241de4fba435.png)

**Comment by RudiDeVos** [comment]
Thanks for the info, that's the risk when you refactor the settings...
Put it on the todo list

**Comment by RudiDeVos** [comment]
I tried to repeat it, but service start as service...

**Comment by Neustradamus** [comment]
@vincentddman: Can you try with 1.4.0.9 version?

@RudiDeVos has tested and has not a problem...

Links:
- 1.4.0.9: https://forum.uvnc.com/viewtopic.php?t=37757
- 1.4.0.10-test: https://forum.uvnc.com/viewtopic.php?p=111533#p111533

**Comment by vincentddman** [comment]
> has tested and has not a problem...

@Neustradamus I use version 1.4.0.9, and there is still a problem with testing

Remarks: As stated in my problem description, you need to make sure that there is no uvnc_service in the windows service, because if there is uvnc_service (regardless of the status of the service), it will be normal

**Comment by RudiDeVos** [comment]
I was able to repeat it

**Comment by RudiDeVos** [comment]
Found
	settings->getAllowEditClients() ? MF_ENABLED : MF_GRAYED);

// IsServiceInstalled use the default uvnc_service name ->RunningFromExternalService
//next 2 lines  need to be removed, are actual not needed

	//if (settings->RunningFromExternalService() && !processHelper::IsServiceInstalled())
	//	settings->RunningFromExternalService(false);

	EnableMenuItem(m_hmenu, ID_CLOSE_SERVICE, (settings->RunningFromExternalService() && settings->getAllowShutdown()) ? MF_ENABLED : MF_GRAYED);

**Comment by RudiDeVos** [comment]
In update 
1.4.2.0
