### ISSUE TITLE
Impossible to save the userID and password of said user while using microsoft AD identification

### ISSUE THREAD

**Issue by Achastel-sataski** [ultravnc/UltraVNC#76]
I have been updating all of my computers to Ultra VNC and I set up the windows AC identification system.

Since that, I have been unable to save my Ids to connect without having to write it up all the time.

When I try to save my connection information, it does ask me if I want to save the password, I do say yes but yet, when I go and use that shortcut to reconnect to the PC, I am asked for my ID and password again.

Is there any way to do what I am trying to do ?

**Comment by RudiDeVos** [comment]
When user + password is used it isn't saved.  Only the uvnc passwd is saved.
The ini files are not secure enough for that kind of info.

But there is a file named UVNC_Launch.exe, this allow you to save the password with a good encryption.
You need to enter a master password on start to be used as key.

**Comment by Neustradamus** [comment]
@Achastel-sataski: I think that this ticket can be closed?

**Comment by Achastel-sataski** [comment]
Yes, the issue is closed, Sorry for not closing it behind me.
Thanks again to @RudiDeVos for the answer.
