### ISSUE TITLE
wrong focus when starting a connection to a server

### ISSUE THREAD

**Issue by JAF84** [ultravnc/UltraVNC#77]
hello,

what has been bothering me for a long time is that when connecting with UltraVNC, i.e., entering the IP address and clicking on "connect", often the focus is not on the password field, but on the "VNC Viewer Status for ...." window. This is, of course, annoying. Is it possible to change this?

br Johannes

**Comment by RudiDeVos** [comment]
I put it on the todo list: verify tabs and focus

**Comment by RudiDeVos** [comment]
done, code added 25/08
