### ISSUE TITLE
Only partial screen shown when connected to Unbuntu

### ISSUE THREAD

**Issue by Craig-Powell** [ultravnc/UltraVNC#78]
In the code change between 1.2.4.0 and 1.3.1rc the display of the remote desktop on my Ubuntu servers broke.  It seems everything from 1.3.1rc and up has this problem, most recently tested with 1.4.0.9.

* tested with default viewer settings
* testing with 64-bit viewer
* windowed/full screen doesn't alter how much of the remote is displayed
* current server I'm testing with is "GNOME Remote Desktop 42.4", up to date Ubuntu Jammy Jellyfish release 22.04.2 LTS

Window I get when connecting via 1.2.4.0:
![UltraVNC-1 2 4 0-working](https://user-images.githubusercontent.com/8678412/226678826-dff73078-f5ab-4dfc-8306-dc7fb8c38b07.png)

Window I get when connecting via 1.3.1rc or above, don't even get scroll bars:
![UltraVNC-1 3 1rc+-broken](https://user-images.githubusercontent.com/8678412/226679065-def09062-4c3e-4fe9-9a8b-e74354c9589b.png)

**Comment by Craig-Powell** [comment]
Additional note which may be relevant, the server I'm connecting to is effectively "headless" since I keep the monitor powered off unless I am at the console. I have not yet tried connecting with the monitor powered on.

Still, this works properly in UltraVNC 1.2.4.0 or earlier, and TigerVNC (1.13.1) but unfortunately TigerVNC does not support scaling which is something I need. RealVNC viewer (7.0.1), which also supports scaling, does not work. RealVNC explicitly states they [may have problems in headless Linux configurations](https://help.realvnc.com/hc/en-us/articles/360005081572-Display-issues-when-connecting-to-VNC-Server-running-on-Linux).

**Comment by Vraana** [comment]
I'm using head...full? :-)
Tried on two different machines and a VM, the same everywhere. Not depending on resolution, always visible only 800x600 (I think)
When I connect using remmina (from Linux) as a client, it works.

**Comment by Craig-Powell** [comment]
From what I can tell the VNC server is "GNOME Remote Desktop 42.4" (https://gitlab.gnome.org/GNOME/gnome-remote-desktop) which looks to be a server of VNC and RDP together.  I think I read previously Ubuntu had utilized vino for the VNC server.  On the plus side to test I think you should be able to just run the Ubuntu image from a bootable thumb drive.  I'll try to confirm this later.

**Comment by Craig-Powell** [comment]
...and it looks like GNOME Remote Desktop utilizes pipewire, if that gets things any closer.

**Comment by Neustradamus** [comment]
@Craig-Powell: Have you seen the last comment from @RudiDeVos?

**Comment by Craig-Powell** [comment]
I did see it but didn't get back to testing.  Also not entirely clear exactly what was being requested to test as the settings look pretty much default.  I have just run the testing I think needed to be done with UltraVNC Viewer 1.4.0.9 and results still have problems.  Tried the following:
* Display tab exactly as Rudi had shown in the example.  All remaining tests start a fresh connection with this state and are changed as noted.
* Checked "Change server resolution" and set the size to match that of the server. (1920x1080)
* Checked "Change Server resolution" (1920x1080) and unchecked "Show toolbar".
* Checked "Change Server resolution" (1920x1080), unchecked "Show toolbar", checked "Start in fullscreen mode".
* Unchecked "Show toolbar".
* Unchecked "Show toolbar" and checked "Start in fullscreen mode".

All of these either gave the same 800x600ish window shown in my first post, or a fullscreen with just the top left 800x600ish being displayed.

If I missed the testing that was being asked please clarify so I can try again later.

**Comment by RudiDeVos** [comment]
![image](https://github.com/ultravnc/UltraVNC/assets/71467484/22a6dd7b-012a-4cb4-b0fa-c28e2592fb30)
Is the naam always "GNOME" ?
The problem is that i need to make a code switch for gnome as this require different handling then other linux distribution.

**Comment by Craig-Powell** [comment]
Wow, I can't say for sure.  I assume that is a value fed by the remote desktop server... definitely isn't my host name.  I'll dig for a config file.

**Comment by Craig-Powell** [comment]
Haven't been able to find anything that indicates where the name is defined, but it may be a moot point in the future anyway.  It appears the gnome remote desktop team is dropping VNC in favor of RDP only by default.
https://gitlab.gnome.org/GNOME/gnome-remote-desktop/-/commit/55ce55afa1ddb502d4c8e13ae813f348d5f76402

**Comment by RudiDeVos** [comment]
On the other hand, adding a switch could be handy. It 's possible that some other servers also work like this.
Gnome always send 800x600 and later he send the real size as ext desktop message. What we didn't handle
as we send our own size... but that isn't supported by GNOME.
Using a switch to handle it or not is a better solution then just a name we get back.

**Comment by Craig-Powell** [comment]
Agreed on the switch vs relying on a name that we don't know where it is coming from. I'm definitely willing to test if you develop an option.

**Comment by RudiDeVos** [comment]
ok, testversion online
https://www.uvnc.eu/download/1400/vncviewer1423dev.zip

**Comment by Craig-Powell** [comment]
Unfortunately no luck.  In this test I first reset all settings to default, then checked the GNOME R. D. box.  Screenshot below.  If I test without that checked it still acts like the second screenshot in my initial post.
![Screenshot 2023-06-22 110338](https://github.com/ultravnc/UltraVNC/assets/8678412/136d7378-9e05-43a0-89ef-dcfa52aefe00)

**Comment by RudiDeVos** [comment]
Damm was working before code cleanup... checking again

**Comment by RudiDeVos** [comment]
Found, was working in debug mode but not in release..some locking between threads blocked all.
Reuploaded file, exe is of today

**Comment by Craig-Powell** [comment]
OK, we have a winner!  Did you include a command line switch for starting with custom options via a shortcut?  E.g., my current shortcut is:
`"UltraVNC Viewer.exe" -scale 3/4 connect localhost::62112`
but that isn't going to work right until I can also toggle the GNOME option.

**Comment by RudiDeVos** [comment]
gnome should work
![image](https://github.com/ultravnc/UltraVNC/assets/71467484/192a941e-fd54-4ea0-b3b4-1c959b2d98a0)

**Comment by Craig-Powell** [comment]
Thanks Rudi, the gnome switch worked in the shortcut.  I had checked the help text that shows when you run the view with /? but hadn't seen it in there.

And I don't know why I had done so, but as you can see in my last post in my shortcut I was using hyphen prefixes on the switches rather than forward slash as is shown on the /? help window.  Seems they are interchangeable?

**Comment by Neustradamus** [comment]
@RudiDeVos: Have you seen the latest @Craig-Powell comment?

**Comment by RudiDeVos** [comment]
done
