### ISSUE TITLE
This site can’t be reached www.uvnc.comdownload unexpectedly closed the connection.

### ISSUE THREAD

**Issue by ifrioct** [ultravnc/UltraVNC#81]
hello, When I try to download vnc server, The web page displays the following: 
This site can’t be reached 
www.uvnc.comdownload unexpectedly closed the connection.
When I try to ping the hostname:
ping uvnc.comdownload
it returns:
ping: cannot resolve uvnc.comdownload: Unknown host

Please tell me how to deal with this situation, can anyone help me! Thanks!

**Comment by RudiDeVos** [comment]
Was solved 02/04/2023.
Check browser cache if you still have it.
