### ISSUE TITLE
after hdd crash cant find a way to re/uninstall

### ISSUE THREAD

**Issue by PixivAddict** [ultravnc/UltraVNC#82]
my D drive stopped working and I cant choose the install directory when trying to reinstall uvnc through the installer.  I cant use the windows uninstaller since it looks for the uninstaller in the non existent d drive.

**Comment by RudiDeVos** [comment]
This is not specific for ultravnc, but all programs that are installed on the crashed d drover going to have this issue.

You need to manual remove the program
See https://support.microsoft.com/en-us/topic/how-to-manually-remove-programs-from-the-add-remove-programs-list-49494159-d215-07b2-e4c7-050457b38352

The installer is doing an update when ultravnc is already installed and this need to be done in the same folder as it was installed.

You can try to overwrite the folder see (UltraVNC_1_4_09_X86_Setup.exe/silent /loadinf="Unattended.txt")
https://forum.uvnc.com/viewtopic.php?p=111495&hilit=unattended#p111495
