### ISSUE TITLE
Website link redirects to some dubious "Your computer is infected with virus -> klick here" page

### ISSUE THREAD

**Issue by hgschwibbe** [ultravnc/UltraVNC#83]
The Website Link on the SSL page redirects to http://adamwalling.com/SecureVNC where I got some Antivirus alert page:
![grafik](https://user-images.githubusercontent.com/1725648/233734303-13e23f12-d84c-4fa2-ac0d-ba7de2235f93.png)

**Comment by Neustradamus** [comment]
@RudiDeVos: Have you seen?

**Comment by RudiDeVos** [comment]
Li!nk removed, seems he didn't extend the domain and now someone else is using it.
