### ISSUE TITLE
if i close the monitor,or lock the windows system .....

### ISSUE THREAD

**Issue by oper1000** [ultravnc/UltraVNC#92]
as the title .....
if i close the monitor,or lock the windows system,and then can i use the ultravnc to link onther ultravnc machine ?

as my test,it tell me can't ,i must wait someone open the monitor or logon the windows system , then i can linked.

so ...can you solve this problem ? thanks a big big big big lot.

**Comment by Neustradamus** [comment]
@RudiDeVos: Have you seen this ticket?

**Comment by oper1000** [comment]
no one care this ?
so,now i use uvnc must keep monitor open,it's really a big trouble.........

**Comment by RudiDeVos** [comment]
I'm sorry but have a lttle problem to understand what you actual want to say.

You can use vnc to login remote if vnc is installed as **service**.
If you start VNC as application your are limited to the current screen.

**Comment by oper1000** [comment]
so your mean .... if i run vnc as a service  ,  then my problem is not a problem ... ?

**Comment by oper1000** [comment]
but when i want start the service in XP ,it display:

![image](https://github.com/ultravnc/UltraVNC/assets/993995/cce9ac7e-c595-4258-8976-643956d6a5ef)

**Comment by RudiDeVos** [comment]
XP ?  Laatest verssion that support 1.2.4.0
https://uvnc.com/
![image](https://github.com/ultravnc/UltraVNC/assets/71467484/c405747b-d51a-4eed-9fd5-6d31749c3257)

**Comment by oper1000** [comment]
the version upper is 1.2.4.0 . although though it display some warning,but it works.

without open the monitor, it connected !  tks a lot.
