### ISSUE TITLE
uvnc services doesn't start

### ISSUE THREAD

**Issue by jochen1727** [ultravnc/UltraVNC#93]
I have installed uvnc through GPO with uvnc executable as service.
Uvnc is installed on my machines but when I start my pc service isn't started.
However as system right my service should start even if my user is not admin.
My machines are on Windows 11.
uvnc has to start to open ports but no start and no any open ports and no connection.
Any ideas about this behavior ?
Thks

**Comment by jochen1727** [comment]
I have installed uvnc through GPO with uvnc executable as service.
Uvnc is installed on my machines but when I start my pc service isn't started.
However as system right my service should start even if my user is not admin.
My machines are on Windows 11.
uvnc has to start to open ports but no start and no any open ports and no connection.
Any ideas about this behavior ?
Thks

**Comment by Neustradamus** [comment]
@RudiDeVos: Have you seen this ticket?

**Comment by RudiDeVos** [comment]
What happen when you execute on a commanline ( as admin)
net start uvnc_service
net stop uvnc_service


The service start after boot, like any other service.
Service can be running and port is blocked, you can't connect, but service is running

Please check.. is the problem no service or not able to connect.

**Comment by RudiDeVos** [comment]
A service van only be installed/started and stopped by an administrator, a normal user can't do it.
Thats how the security from the OS works.

If the service need to be available for a normal user you need to set it to autostart

![image](https://github.com/ultravnc/UltraVNC/assets/71467484/054fa087-dd6d-4d4b-ae1d-742a882470e0)

**Comment by jochen1727** [comment]
thks rudi for your reply,
My service is set to autostart, but it stop wantonly.
And sometimes it doesn't start at startup.
When the service is set to autostart, do my user need admin rights to restart automatically, because a service start with system rigths ?
thks

**Comment by RudiDeVos** [comment]
The desktop user rights have no influence if you start vnc as service.
 
After boot, does net stop uvnc_service say the service is't running ?
_it stop wantonly._ sorry, don't understand this

**Comment by Neustradamus** [comment]
@jochen1727: What do you want to say with "but it stop wantonly"

**Comment by Neustradamus** [comment]
@jochen1727: Have you seen previous answers?

**Comment by RudiDeVos** [comment]
SERvice require admin access to start and stop OS requirement
