### ISSUE TITLE
Unable to download UltraVNC from UVNC website

### ISSUE THREAD

**Issue by krystofkrticka** [ultravnc/UltraVNC#94]
@RudiDeVos
Hello,
when I try to download UltraVNC 1.4.3.0 from official website which is uvnc.com it ends with 404 when it redirects to uvnc.eu which is used as file hosting that `https://www.uvnc.eu/download/1400/UltraVNC_1_4_30_X64_Setup.exe` file `UltraVNC_1_4_30_X64_Setup.exe` does not exist but when I try alternative URL in winget's manifest the file downloads just fine but `https://www.uvnc.eu/download/1400/UltraVNC_1_4_3_0_X64_Setup.exe` the downloaded file has file name `UltraVNC_1_4_3_0_X64_Setup.exe` so maybe mistake happened when uploading installer to file hosting.

**Comment by RudiDeVos** [comment]
Thanks, corrected
