### ISSUE TITLE
how can  i signature when i complete compile from the source code

### ISSUE THREAD

**Issue by oper1000** [ultravnc/UltraVNC#95]
as the title 

![image](https://github.com/ultravnc/UltraVNC/assets/993995/c1e2459b-be9d-4696-a481-ed3b856c8c48)

when i finished compile , how can i do the signature .

and .... if i not signature , What is the difference between the version you released on Github

**Comment by RudiDeVos** [comment]
You can't.
The signature is a stamp that we put to prove the code is compiled by us.

It depend on your compiler, code is 100% the same, but the sdk and compiler you use can be differ then the one we used to make the release.

**Comment by oper1000** [comment]
yes,yes,i know when i download the code and make some modify,it must different with your code on github.

my mean is . if i finish modify the code ,and compiler to a exe file without signture. can it run on x64 windows 10? i know some driver file or services must signture then can run . so if ultravnc all function without signture can be run on windows same as signture?

and anthor question , you make signture need pay money? or it free ?can you tell me what tool you used to signture?

tks a lot !

**Comment by RudiDeVos** [comment]
Yes, the code run without signing, you only get a popup that it isn't signed.

signtool
You need to get a signing certificat ( like ssl for websites, but for signing code)  
Takes a few weeks till month to get cleared, costs around 250/year

**Comment by oper1000** [comment]
and  last question , so  may i download the code ,and make some modify ,and Submit a branch merge in Github？

**Comment by RudiDeVos** [comment]
Yes, UltaVNC is opensource you can make changes, if it get merged or not depend on the changes.
