### ISSUE TITLE
Rising handles on winvnc service (handle leak)

### ISSUE THREAD

**Issue by anja8awe** [ultravnc/UltraVNC#96]
I've got various computers, running SCADA Software 24/7 on Windows10. UltraVNC running as a service with eitehr one or multiple connections. Now I have detected a rising system load on **one of the two** listed winvnc processes.

Given time, the registered handles on the active service is increasing and even hitting system limits. In my current example it was >1.500.000 handles after about 4 days of uptime. When client contacted me the first time, system was close to crash, I've got no data about that event though.

**Facts I know yet:**
- logfile has no errors / no warnings
- allow loopback connection enabled/disables -> No difference
- occuring on various computers with Windows 10 x64 22H2
- Ultra VNC Versions: 1.4.2.0 and 1.4.0.9  (64bit)
- Testing on v1.4.3.0 -> rising handles, looks similar

Any data I can provide?

![git3](https://github.com/ultravnc/UltraVNC/assets/125347105/e6eb4d14-df92-47be-8329-971f9d8eb53c)
![git1](https://github.com/ultravnc/UltraVNC/assets/125347105/de1a741e-a260-42f9-9cbe-666d79505c1c)
![git2](https://github.com/ultravnc/UltraVNC/assets/125347105/3e612d4f-0df5-4b3f-a347-d945de601158)

**Comment by RudiDeVos** [comment]
I was looking for a long time for this, but always checking the winvnc running not as service ( not in session0)
Thanks for yhe feedback, gonna check this asap

**Comment by RudiDeVos** [comment]
Found and commited

**Comment by RudiDeVos** [comment]
Has been added to 1.4.3.1
