### ISSUE TITLE
the screen is too small

### ISSUE THREAD

**Issue by oper1000** [ultravnc/UltraVNC#98]
![image](https://github.com/ultravnc/UltraVNC/assets/993995/2ee705a1-635a-4d29-849c-27a678d17ccf)

as the picture,the remote screen is too small.when i try to use the icon_menu to adjust the screen,it's zoom to big,but It's too blurry

Is there no way to adjust the resolution of the remote screen?

![image](https://github.com/ultravnc/UltraVNC/assets/993995/4c27c307-5ac5-45be-ae82-b1f8aca4cd6c)

**Comment by RudiDeVos** [comment]
![image](https://github.com/ultravnc/UltraVNC/assets/71467484/141fd61c-a764-4ffb-903d-c3ee10b33b60)

**Comment by Neustradamus** [comment]
@oper1000: Have you seen the @RudiDeVos answer?

**Comment by oper1000** [comment]
i'm sorry long time no answer.
yes ,i see  @RudiDeVos answer,but i have tryed and not useful.
it still small after linked remote desktop.
anyway,thanks for answer !

**Comment by oper1000** [comment]
no....try it now!

**Comment by oper1000** [comment]
Remote Machine used 1.4.3.0

![image](https://github.com/ultravnc/UltraVNC/assets/993995/13d535d9-8206-4c41-908b-a9c8757875db)

**Comment by oper1000** [comment]
Oh,i just tryed adjust the remote machine's resolution ratio,it worked!
That's Amazing

**Comment by Neustradamus** [comment]
@oper1000: This ticket can be closed? If yes, please do it!

**Comment by ArtemSydun** [comment]
<img width="594" height="669" alt="Image" src="https://github.com/user-attachments/assets/53818a5f-3694-45ed-b457-521134fd0b7c" />

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/f8351f5e-aca5-41be-903f-682775468620" />

It cuts screen so much, that I can't use the system...
